// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: utilities/proto/events.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UniversalQuery struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to QueryType:
	//
	//	*UniversalQuery_Relational
	//	*UniversalQuery_Document
	//	*UniversalQuery_KeyValue
	QueryType     isUniversalQuery_QueryType `protobuf_oneof:"query_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UniversalQuery) Reset() {
	*x = UniversalQuery{}
	mi := &file_utilities_proto_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UniversalQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniversalQuery) ProtoMessage() {}

func (x *UniversalQuery) ProtoReflect() protoreflect.Message {
	mi := &file_utilities_proto_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniversalQuery.ProtoReflect.Descriptor instead.
func (*UniversalQuery) Descriptor() ([]byte, []int) {
	return file_utilities_proto_events_proto_rawDescGZIP(), []int{0}
}

func (x *UniversalQuery) GetQueryType() isUniversalQuery_QueryType {
	if x != nil {
		return x.QueryType
	}
	return nil
}

func (x *UniversalQuery) GetRelational() *RelationalQuery {
	if x != nil {
		if x, ok := x.QueryType.(*UniversalQuery_Relational); ok {
			return x.Relational
		}
	}
	return nil
}

func (x *UniversalQuery) GetDocument() *DocumentQuery {
	if x != nil {
		if x, ok := x.QueryType.(*UniversalQuery_Document); ok {
			return x.Document
		}
	}
	return nil
}

func (x *UniversalQuery) GetKeyValue() *KeyValueQuery {
	if x != nil {
		if x, ok := x.QueryType.(*UniversalQuery_KeyValue); ok {
			return x.KeyValue
		}
	}
	return nil
}

type isUniversalQuery_QueryType interface {
	isUniversalQuery_QueryType()
}

type UniversalQuery_Relational struct {
	Relational *RelationalQuery `protobuf:"bytes,1,opt,name=relational,proto3,oneof"` // PostgreSQL, MySQL, SQLite
}

type UniversalQuery_Document struct {
	Document *DocumentQuery `protobuf:"bytes,2,opt,name=document,proto3,oneof"` // MongoDB
}

type UniversalQuery_KeyValue struct {
	KeyValue *KeyValueQuery `protobuf:"bytes,3,opt,name=key_value,json=keyValue,proto3,oneof"` // Redis
}

func (*UniversalQuery_Relational) isUniversalQuery_QueryType() {}

func (*UniversalQuery_Document) isUniversalQuery_QueryType() {}

func (*UniversalQuery_KeyValue) isUniversalQuery_QueryType() {}

type RelationalQuery struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Operation        string                 `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	Table            string                 `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	Conditions       []*QueryCondition      `protobuf:"bytes,3,rep,name=conditions,proto3" json:"conditions,omitempty"`
	Fields           []*QueryField          `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty"`
	Limit            int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset           int32                  `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`
	Distinct         bool                   `protobuf:"varint,34,opt,name=distinct,proto3" json:"distinct,omitempty"`
	TransactionId    string                 `protobuf:"bytes,35,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Joins            []*JoinClause          `protobuf:"bytes,7,rep,name=joins,proto3" json:"joins,omitempty"`
	Aggregate        *AggregateClause       `protobuf:"bytes,8,opt,name=aggregate,proto3" json:"aggregate,omitempty"`
	GroupBy          []string               `protobuf:"bytes,9,rep,name=group_by,json=groupBy,proto3" json:"group_by,omitempty"`
	Having           []*QueryCondition      `protobuf:"bytes,10,rep,name=having,proto3" json:"having,omitempty"`
	OrderBy          []*OrderByClause       `protobuf:"bytes,11,rep,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	SavepointName    string                 `protobuf:"bytes,12,opt,name=savepoint_name,json=savepointName,proto3" json:"savepoint_name,omitempty"`
	Permissions      []string               `protobuf:"bytes,13,rep,name=permissions,proto3" json:"permissions,omitempty"`
	PermissionTarget string                 `protobuf:"bytes,14,opt,name=permission_target,json=permissionTarget,proto3" json:"permission_target,omitempty"`
	RoleName         string                 `protobuf:"bytes,15,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	WindowFunctions  []*WindowClause        `protobuf:"bytes,16,rep,name=window_functions,json=windowFunctions,proto3" json:"window_functions,omitempty"`
	Cte              *CTEClause             `protobuf:"bytes,17,opt,name=cte,proto3" json:"cte,omitempty"`
	Subquery         *SubqueryClause        `protobuf:"bytes,18,opt,name=subquery,proto3" json:"subquery,omitempty"`
	Pattern          string                 `protobuf:"bytes,19,opt,name=pattern,proto3" json:"pattern,omitempty"`
	CaseWhen         *CaseClause            `protobuf:"bytes,20,opt,name=case_when,json=caseWhen,proto3" json:"case_when,omitempty"`
	IsolationLevel   string                 `protobuf:"bytes,21,opt,name=isolation_level,json=isolationLevel,proto3" json:"isolation_level,omitempty"`
	ReadOnly         bool                   `protobuf:"varint,22,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	Upsert           *UpsertClause          `protobuf:"bytes,23,opt,name=upsert,proto3" json:"upsert,omitempty"`
	BulkData         []*BulkInsertRow       `protobuf:"bytes,24,rep,name=bulk_data,json=bulkData,proto3" json:"bulk_data,omitempty"`
	ViewName         string                 `protobuf:"bytes,25,opt,name=view_name,json=viewName,proto3" json:"view_name,omitempty"`
	ViewQuery        string                 `protobuf:"bytes,26,opt,name=view_query,json=viewQuery,proto3" json:"view_query,omitempty"`
	DatabaseName     string                 `protobuf:"bytes,27,opt,name=database_name,json=databaseName,proto3" json:"database_name,omitempty"`
	NewName          string                 `protobuf:"bytes,28,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
	UserName         string                 `protobuf:"bytes,29,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Password         string                 `protobuf:"bytes,30,opt,name=password,proto3" json:"password,omitempty"`
	UserRoles        []string               `protobuf:"bytes,31,rep,name=user_roles,json=userRoles,proto3" json:"user_roles,omitempty"`
	SetOperation     *SetOperationClause    `protobuf:"bytes,32,opt,name=set_operation,json=setOperation,proto3" json:"set_operation,omitempty"`
	Columns          []string               `protobuf:"bytes,33,rep,name=columns,proto3" json:"columns,omitempty"`
	SelectColumns    []*SelectColumn        `protobuf:"bytes,36,rep,name=select_columns,json=selectColumns,proto3" json:"select_columns,omitempty"`
	SessionId        string                 `protobuf:"bytes,37,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RelationalQuery) Reset() {
	*x = RelationalQuery{}
	mi := &file_utilities_proto_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationalQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationalQuery) ProtoMessage() {}

func (x *RelationalQuery) ProtoReflect() protoreflect.Message {
	mi := &file_utilities_proto_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationalQuery.ProtoReflect.Descriptor instead.
func (*RelationalQuery) Descriptor() ([]byte, []int) {
	return file_utilities_proto_events_proto_rawDescGZIP(), []int{1}
}

func (x *RelationalQuery) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *RelationalQuery) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *RelationalQuery) GetConditions() []*QueryCondition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *RelationalQuery) GetFields() []*QueryField {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *RelationalQuery) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *RelationalQuery) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *RelationalQuery) GetDistinct() bool {
	if x != nil {
		return x.Distinct
	}
	return false
}

func (x *RelationalQuery) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *RelationalQuery) GetJoins() []*JoinClause {
	if x != nil {
		return x.Joins
	}
	return nil
}

func (x *RelationalQuery) GetAggregate() *AggregateClause {
	if x != nil {
		return x.Aggregate
	}
	return nil
}

func (x *RelationalQuery) GetGroupBy() []string {
	if x != nil {
		return x.GroupBy
	}
	return nil
}

func (x *RelationalQuery) GetHaving() []*QueryCondition {
	if x != nil {
		return x.Having
	}
	return nil
}

func (x *RelationalQuery) GetOrderBy() []*OrderByClause {
	if x != nil {
		return x.OrderBy
	}
	return nil
}

func (x *RelationalQuery) GetSavepointName() string {
	if x != nil {
		return x.SavepointName
	}
	return ""
}

func (x *RelationalQuery) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *RelationalQuery) GetPermissionTarget() string {
	if x != nil {
		return x.PermissionTarget
	}
	return ""
}

func (x *RelationalQuery) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *RelationalQuery) GetWindowFunctions() []*WindowClause {
	if x != nil {
		return x.WindowFunctions
	}
	return nil
}

func (x *RelationalQuery) GetCte() *CTEClause {
	if x != nil {
		return x.Cte
	}
	return nil
}

func (x *RelationalQuery) GetSubquery() *SubqueryClause {
	if x != nil {
		return x.Subquery
	}
	return nil
}

func (x *RelationalQuery) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *RelationalQuery) GetCaseWhen() *CaseClause {
	if x != nil {
		return x.CaseWhen
	}
	return nil
}

func (x *RelationalQuery) GetIsolationLevel() string {
	if x != nil {
		return x.IsolationLevel
	}
	return ""
}

func (x *RelationalQuery) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

func (x *RelationalQuery) GetUpsert() *UpsertClause {
	if x != nil {
		return x.Upsert
	}
	return nil
}

func (x *RelationalQuery) GetBulkData() []*BulkInsertRow {
	if x != nil {
		return x.BulkData
	}
	return nil
}

func (x *RelationalQuery) GetViewName() string {
	if x != nil {
		return x.ViewName
	}
	return ""
}

func (x *RelationalQuery) GetViewQuery() string {
	if x != nil {
		return x.ViewQuery
	}
	return ""
}

func (x *RelationalQuery) GetDatabaseName() string {
	if x != nil {
		return x.DatabaseName
	}
	return ""
}

func (x *RelationalQuery) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

func (x *RelationalQuery) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *RelationalQuery) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RelationalQuery) GetUserRoles() []string {
	if x != nil {
		return x.UserRoles
	}
	return nil
}

func (x *RelationalQuery) GetSetOperation() *SetOperationClause {
	if x != nil {
		return x.SetOperation
	}
	return nil
}

func (x *RelationalQuery) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *RelationalQuery) GetSelectColumns() []*SelectColumn {
	if x != nil {
		return x.SelectColumns
	}
	return nil
}

func (x *RelationalQuery) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type DocumentQuery struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Operation        string                 `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	Collection       string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	Conditions       []*QueryCondition      `protobuf:"bytes,3,rep,name=conditions,proto3" json:"conditions,omitempty"`
	Fields           []*QueryField          `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty"`
	Limit            int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Skip             int32                  `protobuf:"varint,6,opt,name=skip,proto3" json:"skip,omitempty"`
	Joins            []*JoinClause          `protobuf:"bytes,7,rep,name=joins,proto3" json:"joins,omitempty"`
	Aggregate        *AggregateClause       `protobuf:"bytes,8,opt,name=aggregate,proto3" json:"aggregate,omitempty"`
	GroupBy          []string               `protobuf:"bytes,9,rep,name=group_by,json=groupBy,proto3" json:"group_by,omitempty"`
	OrderBy          []*OrderByClause       `protobuf:"bytes,10,rep,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	SavepointName    string                 `protobuf:"bytes,11,opt,name=savepoint_name,json=savepointName,proto3" json:"savepoint_name,omitempty"`
	Permissions      []string               `protobuf:"bytes,12,rep,name=permissions,proto3" json:"permissions,omitempty"`
	PermissionTarget string                 `protobuf:"bytes,13,opt,name=permission_target,json=permissionTarget,proto3" json:"permission_target,omitempty"`
	RoleName         string                 `protobuf:"bytes,14,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	WindowFunctions  []*WindowClause        `protobuf:"bytes,15,rep,name=window_functions,json=windowFunctions,proto3" json:"window_functions,omitempty"`
	Pattern          string                 `protobuf:"bytes,16,opt,name=pattern,proto3" json:"pattern,omitempty"`
	CaseWhen         *CaseClause            `protobuf:"bytes,17,opt,name=case_when,json=caseWhen,proto3" json:"case_when,omitempty"`
	IsolationLevel   string                 `protobuf:"bytes,18,opt,name=isolation_level,json=isolationLevel,proto3" json:"isolation_level,omitempty"`
	ReadOnly         bool                   `protobuf:"varint,19,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	Upsert           *UpsertClause          `protobuf:"bytes,20,opt,name=upsert,proto3" json:"upsert,omitempty"`
	BulkData         []*BulkInsertRow       `protobuf:"bytes,21,rep,name=bulk_data,json=bulkData,proto3" json:"bulk_data,omitempty"`
	ViewName         string                 `protobuf:"bytes,22,opt,name=view_name,json=viewName,proto3" json:"view_name,omitempty"`
	ViewQuery        string                 `protobuf:"bytes,23,opt,name=view_query,json=viewQuery,proto3" json:"view_query,omitempty"`
	DatabaseName     string                 `protobuf:"bytes,24,opt,name=database_name,json=databaseName,proto3" json:"database_name,omitempty"`
	UserName         string                 `protobuf:"bytes,25,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Password         string                 `protobuf:"bytes,26,opt,name=password,proto3" json:"password,omitempty"`
	UserRoles        []string               `protobuf:"bytes,27,rep,name=user_roles,json=userRoles,proto3" json:"user_roles,omitempty"`
	NewName          string                 `protobuf:"bytes,28,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
	SetOperation     *SetOperationClause    `protobuf:"bytes,29,opt,name=set_operation,json=setOperation,proto3" json:"set_operation,omitempty"`
	Columns          []string               `protobuf:"bytes,30,rep,name=columns,proto3" json:"columns,omitempty"`
	SelectColumns    []*SelectColumn        `protobuf:"bytes,31,rep,name=select_columns,json=selectColumns,proto3" json:"select_columns,omitempty"`
	SessionId        string                 `protobuf:"bytes,32,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Having           []*QueryCondition      `protobuf:"bytes,33,rep,name=having,proto3" json:"having,omitempty"`
	Distinct         bool                   `protobuf:"varint,34,opt,name=distinct,proto3" json:"distinct,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DocumentQuery) Reset() {
	*x = DocumentQuery{}
	mi := &file_utilities_proto_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentQuery) ProtoMessage() {}

func (x *DocumentQuery) ProtoReflect() protoreflect.Message {
	mi := &file_utilities_proto_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentQuery.ProtoReflect.Descriptor instead.
func (*DocumentQuery) Descriptor() ([]byte, []int) {
	return file_utilities_proto_events_proto_rawDescGZIP(), []int{2}
}

func (x *DocumentQuery) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *DocumentQuery) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *DocumentQuery) GetConditions() []*QueryCondition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *DocumentQuery) GetFields() []*QueryField {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *DocumentQuery) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *DocumentQuery) GetSkip() int32 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *DocumentQuery) GetJoins() []*JoinClause {
	if x != nil {
		return x.Joins
	}
	return nil
}

func (x *DocumentQuery) GetAggregate() *AggregateClause {
	if x != nil {
		return x.Aggregate
	}
	return nil
}

func (x *DocumentQuery) GetGroupBy() []string {
	if x != nil {
		return x.GroupBy
	}
	return nil
}

func (x *DocumentQuery) GetOrderBy() []*OrderByClause {
	if x != nil {
		return x.OrderBy
	}
	return nil
}

func (x *DocumentQuery) GetSavepointName() string {
	if x != nil {
		return x.SavepointName
	}
	return ""
}

func (x *DocumentQuery) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *DocumentQuery) GetPermissionTarget() string {
	if x != nil {
		return x.PermissionTarget
	}
	return ""
}

func (x *DocumentQuery) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *DocumentQuery) GetWindowFunctions() []*WindowClause {
	if x != nil {
		return x.WindowFunctions
	}
	return nil
}

func (x *DocumentQuery) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *DocumentQuery) GetCaseWhen() *CaseClause {
	if x != nil {
		return x.CaseWhen
	}
	return nil
}

func (x *DocumentQuery) GetIsolationLevel() string {
	if x != nil {
		return x.IsolationLevel
	}
	return ""
}

func (x *DocumentQuery) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

func (x *DocumentQuery) GetUpsert() *UpsertClause {
	if x != nil {
		return x.Upsert
	}
	return nil
}

func (x *DocumentQuery) GetBulkData() []*BulkInsertRow {
	if x != nil {
		return x.BulkData
	}
	return nil
}

func (x *DocumentQuery) GetViewName() string {
	if x != nil {
		return x.ViewName
	}
	return ""
}

func (x *DocumentQuery) GetViewQuery() string {
	if x != nil {
		return x.ViewQuery
	}
	return ""
}

func (x *DocumentQuery) GetDatabaseName() string {
	if x != nil {
		return x.DatabaseName
	}
	return ""
}

func (x *DocumentQuery) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *DocumentQuery) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *DocumentQuery) GetUserRoles() []string {
	if x != nil {
		return x.UserRoles
	}
	return nil
}

func (x *DocumentQuery) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

func (x *DocumentQuery) GetSetOperation() *SetOperationClause {
	if x != nil {
		return x.SetOperation
	}
	return nil
}

func (x *DocumentQuery) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *DocumentQuery) GetSelectColumns() []*SelectColumn {
	if x != nil {
		return x.SelectColumns
	}
	return nil
}

func (x *DocumentQuery) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DocumentQuery) GetHaving() []*QueryCondition {
	if x != nil {
		return x.Having
	}
	return nil
}

func (x *DocumentQuery) GetDistinct() bool {
	if x != nil {
		return x.Distinct
	}
	return false
}

type KeyValueQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Args          []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	BulkPairs     []*KeyValuePair        `protobuf:"bytes,4,rep,name=bulk_pairs,json=bulkPairs,proto3" json:"bulk_pairs,omitempty"`
	SessionId     string                 `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValueQuery) Reset() {
	*x = KeyValueQuery{}
	mi := &file_utilities_proto_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValueQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValueQuery) ProtoMessage() {}

func (x *KeyValueQuery) ProtoReflect() protoreflect.Message {
	mi := &file_utilities_proto_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValueQuery.ProtoReflect.Descriptor instead.
func (*KeyValueQuery) Descriptor() ([]byte, []int) {
	return file_utilities_proto_events_proto_rawDescGZIP(), []int{3}
}

func (x *KeyValueQuery) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *KeyValueQuery) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValueQuery) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *KeyValueQuery) GetBulkPairs() []*KeyValuePair {
	if x != nil {
		return x.BulkPairs
	}
	return nil
}

func (x *KeyValueQuery) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type KeyValuePair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValuePair) Reset() {
	*x = KeyValuePair{}
	mi := &file_utilities_proto_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValuePair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValuePair) ProtoMessage() {}

func (x *KeyValuePair) ProtoReflect() protoreflect.Message {
	mi := &file_utilities_proto_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValuePair.ProtoReflect.Descriptor instead.
func (*KeyValuePair) Descriptor() ([]byte, []int) {
	return file_utilities_proto_events_proto_rawDescGZIP(), []int{4}
}

func (x *KeyValuePair) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValuePair) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type QueryCondition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Operator      string                 `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryCondition) Reset() {
	*x = QueryCondition{}
	mi := &file_utilities_proto_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryCondition) ProtoMessage() {}

func (x *QueryCondition) ProtoReflect() protoreflect.Message {
	mi := &file_utilities_proto_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryCondition.ProtoReflect.Descriptor instead.
func (*QueryCondition) Descriptor() ([]byte, []int) {
	return file_utilities_proto_events_proto_rawDescGZIP(), []int{5}
}

func (x *QueryCondition) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *QueryCondition) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *QueryCondition) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type QueryField struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value       string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Constraints []string               `protobuf:"bytes,3,rep,name=constraints,proto3" json:"constraints,omitempty"`
	// Types that are valid to be assigned to FieldType:
	//
	//	*QueryField_LiteralValue
	//	*QueryField_Expression
	FieldType     isQueryField_FieldType `protobuf_oneof:"field_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryField) Reset() {
	*x = QueryField{}
	mi := &file_utilities_proto_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryField) ProtoMessage() {}

func (x *QueryField) ProtoReflect() protoreflect.Message {
	mi := &file_utilities_proto_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryField.ProtoReflect.Descriptor instead.
func (*QueryField) Descriptor() ([]byte, []int) {
	return file_utilities_proto_events_proto_rawDescGZIP(), []int{6}
}

func (x *QueryField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QueryField) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *QueryField) GetConstraints() []string {
	if x != nil {
		return x.Constraints
	}
	return nil
}

func (x *QueryField) GetFieldType() isQueryField_FieldType {
	if x != nil {
		return x.FieldType
	}
	return nil
}

func (x *QueryField) GetLiteralValue() string {
	if x != nil {
		if x, ok := x.FieldType.(*QueryField_LiteralValue); ok {
			return x.LiteralValue
		}
	}
	return ""
}

func (x *QueryField) GetExpression() *FieldExpression {
	if x != nil {
		if x, ok := x.FieldType.(*QueryField_Expression); ok {
			return x.Expression
		}
	}
	return nil
}

type isQueryField_FieldType interface {
	isQueryField_FieldType()
}

type QueryField_LiteralValue struct {
	LiteralValue string `protobuf:"bytes,4,opt,name=literal_value,json=literalValue,proto3,oneof"`
}

type QueryField_Expression struct {
	Expression *FieldExpression `protobuf:"bytes,5,opt,name=expression,proto3,oneof"`
}

func (*QueryField_LiteralValue) isQueryField_FieldType() {}

func (*QueryField_Expression) isQueryField_FieldType() {}

type FieldExpression struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ExpressionType string                 `protobuf:"bytes,1,opt,name=expression_type,json=expressionType,proto3" json:"expression_type,omitempty"`
	LeftOperand    string                 `protobuf:"bytes,2,opt,name=left_operand,json=leftOperand,proto3" json:"left_operand,omitempty"`
	Operator       string                 `protobuf:"bytes,3,opt,name=operator,proto3" json:"operator,omitempty"`
	RightOperand   string                 `protobuf:"bytes,4,opt,name=right_operand,json=rightOperand,proto3" json:"right_operand,omitempty"`
	LeftIsField    bool                   `protobuf:"varint,5,opt,name=left_is_field,json=leftIsField,proto3" json:"left_is_field,omitempty"`
	RightIsField   bool                   `protobuf:"varint,6,opt,name=right_is_field,json=rightIsField,proto3" json:"right_is_field,omitempty"`
	FunctionName   string                 `protobuf:"bytes,7,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"`
	FunctionArgs   []string               `protobuf:"bytes,8,rep,name=function_args,json=functionArgs,proto3" json:"function_args,omitempty"`
	CaseConditions []*CaseCondition       `protobuf:"bytes,9,rep,name=case_conditions,json=caseConditions,proto3" json:"case_conditions,omitempty"`
	CaseElse       string                 `protobuf:"bytes,10,opt,name=case_else,json=caseElse,proto3" json:"case_else,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FieldExpression) Reset() {
	*x = FieldExpression{}
	mi := &file_utilities_proto_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldExpression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldExpression) ProtoMessage() {}

func (x *FieldExpression) ProtoReflect() protoreflect.Message {
	mi := &file_utilities_proto_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldExpression.ProtoReflect.Descriptor instead.
func (*FieldExpression) Descriptor() ([]byte, []int) {
	return file_utilities_proto_events_proto_rawDescGZIP(), []int{7}
}

func (x *FieldExpression) GetExpressionType() string {
	if x != nil {
		return x.ExpressionType
	}
	return ""
}

func (x *FieldExpression) GetLeftOperand() string {
	if x != nil {
		return x.LeftOperand
	}
	return ""
}

func (x *FieldExpression) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *FieldExpression) GetRightOperand() string {
	if x != nil {
		return x.RightOperand
	}
	return ""
}

func (x *FieldExpression) GetLeftIsField() bool {
	if x != nil {
		return x.LeftIsField
	}
	return false
}

func (x *FieldExpression) GetRightIsField() bool {
	if x != nil {
		return x.RightIsField
	}
	return false
}

func (x *FieldExpression) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

func (x *FieldExpression) GetFunctionArgs() []string {
	if x != nil {
		return x.FunctionArgs
	}
	return nil
}

func (x *FieldExpression) GetCaseConditions() []*CaseCondition {
	if x != nil {
		return x.CaseConditions
	}
	return nil
}

func (x *FieldExpression) GetCaseElse() string {
	if x != nil {
		return x.CaseElse
	}
	return ""
}

type CaseCondition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Condition     string                 `protobuf:"bytes,1,opt,name=condition,proto3" json:"condition,omitempty"`
	ThenValue     string                 `protobuf:"bytes,2,opt,name=then_value,json=thenValue,proto3" json:"then_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaseCondition) Reset() {
	*x = CaseCondition{}
	mi := &file_utilities_proto_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaseCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaseCondition) ProtoMessage() {}

func (x *CaseCondition) ProtoReflect() protoreflect.Message {
	mi := &file_utilities_proto_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaseCondition.ProtoReflect.Descriptor instead.
func (*CaseCondition) Descriptor() ([]byte, []int) {
	return file_utilities_proto_events_proto_rawDescGZIP(), []int{8}
}

func (x *CaseCondition) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *CaseCondition) GetThenValue() string {
	if x != nil {
		return x.ThenValue
	}
	return ""
}

type SelectColumn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expression    string                 `protobuf:"bytes,1,opt,name=expression,proto3" json:"expression,omitempty"`
	Alias         string                 `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	ExpressionObj *FieldExpression       `protobuf:"bytes,3,opt,name=expression_obj,json=expressionObj,proto3" json:"expression_obj,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectColumn) Reset() {
	*x = SelectColumn{}
	mi := &file_utilities_proto_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectColumn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectColumn) ProtoMessage() {}

func (x *SelectColumn) ProtoReflect() protoreflect.Message {
	mi := &file_utilities_proto_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectColumn.ProtoReflect.Descriptor instead.
func (*SelectColumn) Descriptor() ([]byte, []int) {
	return file_utilities_proto_events_proto_rawDescGZIP(), []int{9}
}

func (x *SelectColumn) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

func (x *SelectColumn) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *SelectColumn) GetExpressionObj() *FieldExpression {
	if x != nil {
		return x.ExpressionObj
	}
	return nil
}

type JoinClause struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JoinType      string                 `protobuf:"bytes,1,opt,name=join_type,json=joinType,proto3" json:"join_type,omitempty"`
	Table         string                 `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	LeftField     string                 `protobuf:"bytes,3,opt,name=left_field,json=leftField,proto3" json:"left_field,omitempty"`
	RightField    string                 `protobuf:"bytes,4,opt,name=right_field,json=rightField,proto3" json:"right_field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinClause) Reset() {
	*x = JoinClause{}
	mi := &file_utilities_proto_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinClause) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinClause) ProtoMessage() {}

func (x *JoinClause) ProtoReflect() protoreflect.Message {
	mi := &file_utilities_proto_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinClause.ProtoReflect.Descriptor instead.
func (*JoinClause) Descriptor() ([]byte, []int) {
	return file_utilities_proto_events_proto_rawDescGZIP(), []int{10}
}

func (x *JoinClause) GetJoinType() string {
	if x != nil {
		return x.JoinType
	}
	return ""
}

func (x *JoinClause) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *JoinClause) GetLeftField() string {
	if x != nil {
		return x.LeftField
	}
	return ""
}

func (x *JoinClause) GetRightField() string {
	if x != nil {
		return x.RightField
	}
	return ""
}

type AggregateClause struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Function      string                 `protobuf:"bytes,1,opt,name=function,proto3" json:"function,omitempty"`
	Field         string                 `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregateClause) Reset() {
	*x = AggregateClause{}
	mi := &file_utilities_proto_events_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregateClause) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregateClause) ProtoMessage() {}

func (x *AggregateClause) ProtoReflect() protoreflect.Message {
	mi := &file_utilities_proto_events_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregateClause.ProtoReflect.Descriptor instead.
func (*AggregateClause) Descriptor() ([]byte, []int) {
	return file_utilities_proto_events_proto_rawDescGZIP(), []int{11}
}

func (x *AggregateClause) GetFunction() string {
	if x != nil {
		return x.Function
	}
	return ""
}

func (x *AggregateClause) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

type OrderByClause struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Direction     string                 `protobuf:"bytes,2,opt,name=direction,proto3" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderByClause) Reset() {
	*x = OrderByClause{}
	mi := &file_utilities_proto_events_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderByClause) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderByClause) ProtoMessage() {}

func (x *OrderByClause) ProtoReflect() protoreflect.Message {
	mi := &file_utilities_proto_events_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderByClause.ProtoReflect.Descriptor instead.
func (*OrderByClause) Descriptor() ([]byte, []int) {
	return file_utilities_proto_events_proto_rawDescGZIP(), []int{12}
}

func (x *OrderByClause) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *OrderByClause) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

type WindowClause struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Function      string                 `protobuf:"bytes,1,opt,name=function,proto3" json:"function,omitempty"`
	Alias         string                 `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	PartitionBy   []string               `protobuf:"bytes,3,rep,name=partition_by,json=partitionBy,proto3" json:"partition_by,omitempty"`
	OrderBy       []*OrderByClause       `protobuf:"bytes,4,rep,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	Offset        int32                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	Buckets       int32                  `protobuf:"varint,6,opt,name=buckets,proto3" json:"buckets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WindowClause) Reset() {
	*x = WindowClause{}
	mi := &file_utilities_proto_events_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WindowClause) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WindowClause) ProtoMessage() {}

func (x *WindowClause) ProtoReflect() protoreflect.Message {
	mi := &file_utilities_proto_events_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WindowClause.ProtoReflect.Descriptor instead.
func (*WindowClause) Descriptor() ([]byte, []int) {
	return file_utilities_proto_events_proto_rawDescGZIP(), []int{13}
}

func (x *WindowClause) GetFunction() string {
	if x != nil {
		return x.Function
	}
	return ""
}

func (x *WindowClause) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *WindowClause) GetPartitionBy() []string {
	if x != nil {
		return x.PartitionBy
	}
	return nil
}

func (x *WindowClause) GetOrderBy() []*OrderByClause {
	if x != nil {
		return x.OrderBy
	}
	return nil
}

func (x *WindowClause) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *WindowClause) GetBuckets() int32 {
	if x != nil {
		return x.Buckets
	}
	return 0
}

type CTEClause struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CteName        string                 `protobuf:"bytes,1,opt,name=cte_name,json=cteName,proto3" json:"cte_name,omitempty"`
	CteQuery       string                 `protobuf:"bytes,2,opt,name=cte_query,json=cteQuery,proto3" json:"cte_query,omitempty"`
	Recursive      bool                   `protobuf:"varint,3,opt,name=recursive,proto3" json:"recursive,omitempty"`
	AdditionalCtes []*CTEClause           `protobuf:"bytes,4,rep,name=additional_ctes,json=additionalCtes,proto3" json:"additional_ctes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CTEClause) Reset() {
	*x = CTEClause{}
	mi := &file_utilities_proto_events_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CTEClause) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CTEClause) ProtoMessage() {}

func (x *CTEClause) ProtoReflect() protoreflect.Message {
	mi := &file_utilities_proto_events_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CTEClause.ProtoReflect.Descriptor instead.
func (*CTEClause) Descriptor() ([]byte, []int) {
	return file_utilities_proto_events_proto_rawDescGZIP(), []int{14}
}

func (x *CTEClause) GetCteName() string {
	if x != nil {
		return x.CteName
	}
	return ""
}

func (x *CTEClause) GetCteQuery() string {
	if x != nil {
		return x.CteQuery
	}
	return ""
}

func (x *CTEClause) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

func (x *CTEClause) GetAdditionalCtes() []*CTEClause {
	if x != nil {
		return x.AdditionalCtes
	}
	return nil
}

type SubqueryClause struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubqueryType  string                 `protobuf:"bytes,1,opt,name=subquery_type,json=subqueryType,proto3" json:"subquery_type,omitempty"`
	Field         string                 `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	Subquery      string                 `protobuf:"bytes,3,opt,name=subquery,proto3" json:"subquery,omitempty"`
	Alias         string                 `protobuf:"bytes,4,opt,name=alias,proto3" json:"alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubqueryClause) Reset() {
	*x = SubqueryClause{}
	mi := &file_utilities_proto_events_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubqueryClause) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubqueryClause) ProtoMessage() {}

func (x *SubqueryClause) ProtoReflect() protoreflect.Message {
	mi := &file_utilities_proto_events_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubqueryClause.ProtoReflect.Descriptor instead.
func (*SubqueryClause) Descriptor() ([]byte, []int) {
	return file_utilities_proto_events_proto_rawDescGZIP(), []int{15}
}

func (x *SubqueryClause) GetSubqueryType() string {
	if x != nil {
		return x.SubqueryType
	}
	return ""
}

func (x *SubqueryClause) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *SubqueryClause) GetSubquery() string {
	if x != nil {
		return x.Subquery
	}
	return ""
}

func (x *SubqueryClause) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

type CaseClause struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WhenClauses   []*CaseWhen            `protobuf:"bytes,1,rep,name=when_clauses,json=whenClauses,proto3" json:"when_clauses,omitempty"`
	ElseValue     string                 `protobuf:"bytes,2,opt,name=else_value,json=elseValue,proto3" json:"else_value,omitempty"`
	Alias         string                 `protobuf:"bytes,3,opt,name=alias,proto3" json:"alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaseClause) Reset() {
	*x = CaseClause{}
	mi := &file_utilities_proto_events_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaseClause) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaseClause) ProtoMessage() {}

func (x *CaseClause) ProtoReflect() protoreflect.Message {
	mi := &file_utilities_proto_events_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaseClause.ProtoReflect.Descriptor instead.
func (*CaseClause) Descriptor() ([]byte, []int) {
	return file_utilities_proto_events_proto_rawDescGZIP(), []int{16}
}

func (x *CaseClause) GetWhenClauses() []*CaseWhen {
	if x != nil {
		return x.WhenClauses
	}
	return nil
}

func (x *CaseClause) GetElseValue() string {
	if x != nil {
		return x.ElseValue
	}
	return ""
}

func (x *CaseClause) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

type CaseWhen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Condition     string                 `protobuf:"bytes,1,opt,name=condition,proto3" json:"condition,omitempty"`
	ThenValue     string                 `protobuf:"bytes,2,opt,name=then_value,json=thenValue,proto3" json:"then_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaseWhen) Reset() {
	*x = CaseWhen{}
	mi := &file_utilities_proto_events_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaseWhen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaseWhen) ProtoMessage() {}

func (x *CaseWhen) ProtoReflect() protoreflect.Message {
	mi := &file_utilities_proto_events_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaseWhen.ProtoReflect.Descriptor instead.
func (*CaseWhen) Descriptor() ([]byte, []int) {
	return file_utilities_proto_events_proto_rawDescGZIP(), []int{17}
}

func (x *CaseWhen) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *CaseWhen) GetThenValue() string {
	if x != nil {
		return x.ThenValue
	}
	return ""
}

type UpsertClause struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConflictFields []string               `protobuf:"bytes,1,rep,name=conflict_fields,json=conflictFields,proto3" json:"conflict_fields,omitempty"`
	UpdateFields   []*QueryField          `protobuf:"bytes,2,rep,name=update_fields,json=updateFields,proto3" json:"update_fields,omitempty"`
	ConflictAction string                 `protobuf:"bytes,3,opt,name=conflict_action,json=conflictAction,proto3" json:"conflict_action,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpsertClause) Reset() {
	*x = UpsertClause{}
	mi := &file_utilities_proto_events_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertClause) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertClause) ProtoMessage() {}

func (x *UpsertClause) ProtoReflect() protoreflect.Message {
	mi := &file_utilities_proto_events_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertClause.ProtoReflect.Descriptor instead.
func (*UpsertClause) Descriptor() ([]byte, []int) {
	return file_utilities_proto_events_proto_rawDescGZIP(), []int{18}
}

func (x *UpsertClause) GetConflictFields() []string {
	if x != nil {
		return x.ConflictFields
	}
	return nil
}

func (x *UpsertClause) GetUpdateFields() []*QueryField {
	if x != nil {
		return x.UpdateFields
	}
	return nil
}

func (x *UpsertClause) GetConflictAction() string {
	if x != nil {
		return x.ConflictAction
	}
	return ""
}

type BulkInsertRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        []*QueryField          `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkInsertRow) Reset() {
	*x = BulkInsertRow{}
	mi := &file_utilities_proto_events_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkInsertRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkInsertRow) ProtoMessage() {}

func (x *BulkInsertRow) ProtoReflect() protoreflect.Message {
	mi := &file_utilities_proto_events_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkInsertRow.ProtoReflect.Descriptor instead.
func (*BulkInsertRow) Descriptor() ([]byte, []int) {
	return file_utilities_proto_events_proto_rawDescGZIP(), []int{19}
}

func (x *BulkInsertRow) GetFields() []*QueryField {
	if x != nil {
		return x.Fields
	}
	return nil
}

type SetOperationClause struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationType string                 `protobuf:"bytes,1,opt,name=operation_type,json=operationType,proto3" json:"operation_type,omitempty"`
	LeftQuery     *RelationalQuery       `protobuf:"bytes,2,opt,name=left_query,json=leftQuery,proto3" json:"left_query,omitempty"`
	RightQuery    *RelationalQuery       `protobuf:"bytes,3,opt,name=right_query,json=rightQuery,proto3" json:"right_query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetOperationClause) Reset() {
	*x = SetOperationClause{}
	mi := &file_utilities_proto_events_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetOperationClause) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetOperationClause) ProtoMessage() {}

func (x *SetOperationClause) ProtoReflect() protoreflect.Message {
	mi := &file_utilities_proto_events_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetOperationClause.ProtoReflect.Descriptor instead.
func (*SetOperationClause) Descriptor() ([]byte, []int) {
	return file_utilities_proto_events_proto_rawDescGZIP(), []int{20}
}

func (x *SetOperationClause) GetOperationType() string {
	if x != nil {
		return x.OperationType
	}
	return ""
}

func (x *SetOperationClause) GetLeftQuery() *RelationalQuery {
	if x != nil {
		return x.LeftQuery
	}
	return nil
}

func (x *SetOperationClause) GetRightQuery() *RelationalQuery {
	if x != nil {
		return x.RightQuery
	}
	return nil
}

var File_utilities_proto_events_proto protoreflect.FileDescriptor

const file_utilities_proto_events_proto_rawDesc = "" +
	"\n" +
	"\x1cutilities/proto/events.proto\x12\x06omniql\"\xc4\x01\n" +
	"\x0eUniversalQuery\x129\n" +
	"\n" +
	"relational\x18\x01 \x01(\v2\x17.omniql.RelationalQueryH\x00R\n" +
	"relational\x123\n" +
	"\bdocument\x18\x02 \x01(\v2\x15.omniql.DocumentQueryH\x00R\bdocument\x124\n" +
	"\tkey_value\x18\x03 \x01(\v2\x15.omniql.KeyValueQueryH\x00R\bkeyValueB\f\n" +
	"\n" +
	"query_type\"\xa3\v\n" +
	"\x0fRelationalQuery\x12\x1c\n" +
	"\toperation\x18\x01 \x01(\tR\toperation\x12\x14\n" +
	"\x05table\x18\x02 \x01(\tR\x05table\x126\n" +
	"\n" +
	"conditions\x18\x03 \x03(\v2\x16.omniql.QueryConditionR\n" +
	"conditions\x12*\n" +
	"\x06fields\x18\x04 \x03(\v2\x12.omniql.QueryFieldR\x06fields\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x06 \x01(\x05R\x06offset\x12\x1a\n" +
	"\bdistinct\x18\" \x01(\bR\bdistinct\x12%\n" +
	"\x0etransaction_id\x18# \x01(\tR\rtransactionId\x12(\n" +
	"\x05joins\x18\a \x03(\v2\x12.omniql.JoinClauseR\x05joins\x125\n" +
	"\taggregate\x18\b \x01(\v2\x17.omniql.AggregateClauseR\taggregate\x12\x19\n" +
	"\bgroup_by\x18\t \x03(\tR\agroupBy\x12.\n" +
	"\x06having\x18\n" +
	" \x03(\v2\x16.omniql.QueryConditionR\x06having\x120\n" +
	"\border_by\x18\v \x03(\v2\x15.omniql.OrderByClauseR\aorderBy\x12%\n" +
	"\x0esavepoint_name\x18\f \x01(\tR\rsavepointName\x12 \n" +
	"\vpermissions\x18\r \x03(\tR\vpermissions\x12+\n" +
	"\x11permission_target\x18\x0e \x01(\tR\x10permissionTarget\x12\x1b\n" +
	"\trole_name\x18\x0f \x01(\tR\broleName\x12?\n" +
	"\x10window_functions\x18\x10 \x03(\v2\x14.omniql.WindowClauseR\x0fwindowFunctions\x12#\n" +
	"\x03cte\x18\x11 \x01(\v2\x11.omniql.CTEClauseR\x03cte\x122\n" +
	"\bsubquery\x18\x12 \x01(\v2\x16.omniql.SubqueryClauseR\bsubquery\x12\x18\n" +
	"\apattern\x18\x13 \x01(\tR\apattern\x12/\n" +
	"\tcase_when\x18\x14 \x01(\v2\x12.omniql.CaseClauseR\bcaseWhen\x12'\n" +
	"\x0fisolation_level\x18\x15 \x01(\tR\x0eisolationLevel\x12\x1b\n" +
	"\tread_only\x18\x16 \x01(\bR\breadOnly\x12,\n" +
	"\x06upsert\x18\x17 \x01(\v2\x14.omniql.UpsertClauseR\x06upsert\x122\n" +
	"\tbulk_data\x18\x18 \x03(\v2\x15.omniql.BulkInsertRowR\bbulkData\x12\x1b\n" +
	"\tview_name\x18\x19 \x01(\tR\bviewName\x12\x1d\n" +
	"\n" +
	"view_query\x18\x1a \x01(\tR\tviewQuery\x12#\n" +
	"\rdatabase_name\x18\x1b \x01(\tR\fdatabaseName\x12\x19\n" +
	"\bnew_name\x18\x1c \x01(\tR\anewName\x12\x1b\n" +
	"\tuser_name\x18\x1d \x01(\tR\buserName\x12\x1a\n" +
	"\bpassword\x18\x1e \x01(\tR\bpassword\x12\x1d\n" +
	"\n" +
	"user_roles\x18\x1f \x03(\tR\tuserRoles\x12?\n" +
	"\rset_operation\x18  \x01(\v2\x1a.omniql.SetOperationClauseR\fsetOperation\x12\x18\n" +
	"\acolumns\x18! \x03(\tR\acolumns\x12;\n" +
	"\x0eselect_columns\x18$ \x03(\v2\x14.omniql.SelectColumnR\rselectColumns\x12\x1d\n" +
	"\n" +
	"session_id\x18% \x01(\tR\tsessionId\"\xa7\n" +
	"\n" +
	"\rDocumentQuery\x12\x1c\n" +
	"\toperation\x18\x01 \x01(\tR\toperation\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\x126\n" +
	"\n" +
	"conditions\x18\x03 \x03(\v2\x16.omniql.QueryConditionR\n" +
	"conditions\x12*\n" +
	"\x06fields\x18\x04 \x03(\v2\x12.omniql.QueryFieldR\x06fields\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\x12\x12\n" +
	"\x04skip\x18\x06 \x01(\x05R\x04skip\x12(\n" +
	"\x05joins\x18\a \x03(\v2\x12.omniql.JoinClauseR\x05joins\x125\n" +
	"\taggregate\x18\b \x01(\v2\x17.omniql.AggregateClauseR\taggregate\x12\x19\n" +
	"\bgroup_by\x18\t \x03(\tR\agroupBy\x120\n" +
	"\border_by\x18\n" +
	" \x03(\v2\x15.omniql.OrderByClauseR\aorderBy\x12%\n" +
	"\x0esavepoint_name\x18\v \x01(\tR\rsavepointName\x12 \n" +
	"\vpermissions\x18\f \x03(\tR\vpermissions\x12+\n" +
	"\x11permission_target\x18\r \x01(\tR\x10permissionTarget\x12\x1b\n" +
	"\trole_name\x18\x0e \x01(\tR\broleName\x12?\n" +
	"\x10window_functions\x18\x0f \x03(\v2\x14.omniql.WindowClauseR\x0fwindowFunctions\x12\x18\n" +
	"\apattern\x18\x10 \x01(\tR\apattern\x12/\n" +
	"\tcase_when\x18\x11 \x01(\v2\x12.omniql.CaseClauseR\bcaseWhen\x12'\n" +
	"\x0fisolation_level\x18\x12 \x01(\tR\x0eisolationLevel\x12\x1b\n" +
	"\tread_only\x18\x13 \x01(\bR\breadOnly\x12,\n" +
	"\x06upsert\x18\x14 \x01(\v2\x14.omniql.UpsertClauseR\x06upsert\x122\n" +
	"\tbulk_data\x18\x15 \x03(\v2\x15.omniql.BulkInsertRowR\bbulkData\x12\x1b\n" +
	"\tview_name\x18\x16 \x01(\tR\bviewName\x12\x1d\n" +
	"\n" +
	"view_query\x18\x17 \x01(\tR\tviewQuery\x12#\n" +
	"\rdatabase_name\x18\x18 \x01(\tR\fdatabaseName\x12\x1b\n" +
	"\tuser_name\x18\x19 \x01(\tR\buserName\x12\x1a\n" +
	"\bpassword\x18\x1a \x01(\tR\bpassword\x12\x1d\n" +
	"\n" +
	"user_roles\x18\x1b \x03(\tR\tuserRoles\x12\x19\n" +
	"\bnew_name\x18\x1c \x01(\tR\anewName\x12?\n" +
	"\rset_operation\x18\x1d \x01(\v2\x1a.omniql.SetOperationClauseR\fsetOperation\x12\x18\n" +
	"\acolumns\x18\x1e \x03(\tR\acolumns\x12;\n" +
	"\x0eselect_columns\x18\x1f \x03(\v2\x14.omniql.SelectColumnR\rselectColumns\x12\x1d\n" +
	"\n" +
	"session_id\x18  \x01(\tR\tsessionId\x12.\n" +
	"\x06having\x18! \x03(\v2\x16.omniql.QueryConditionR\x06having\x12\x1a\n" +
	"\bdistinct\x18\" \x01(\bR\bdistinct\"\xa3\x01\n" +
	"\rKeyValueQuery\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x123\n" +
	"\n" +
	"bulk_pairs\x18\x04 \x03(\v2\x14.omniql.KeyValuePairR\tbulkPairs\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\"6\n" +
	"\fKeyValuePair\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"X\n" +
	"\x0eQueryCondition\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x1a\n" +
	"\boperator\x18\x02 \x01(\tR\boperator\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"\xc8\x01\n" +
	"\n" +
	"QueryField\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12 \n" +
	"\vconstraints\x18\x03 \x03(\tR\vconstraints\x12%\n" +
	"\rliteral_value\x18\x04 \x01(\tH\x00R\fliteralValue\x129\n" +
	"\n" +
	"expression\x18\x05 \x01(\v2\x17.omniql.FieldExpressionH\x00R\n" +
	"expressionB\f\n" +
	"\n" +
	"field_type\"\x8f\x03\n" +
	"\x0fFieldExpression\x12'\n" +
	"\x0fexpression_type\x18\x01 \x01(\tR\x0eexpressionType\x12!\n" +
	"\fleft_operand\x18\x02 \x01(\tR\vleftOperand\x12\x1a\n" +
	"\boperator\x18\x03 \x01(\tR\boperator\x12#\n" +
	"\rright_operand\x18\x04 \x01(\tR\frightOperand\x12\"\n" +
	"\rleft_is_field\x18\x05 \x01(\bR\vleftIsField\x12$\n" +
	"\x0eright_is_field\x18\x06 \x01(\bR\frightIsField\x12#\n" +
	"\rfunction_name\x18\a \x01(\tR\ffunctionName\x12#\n" +
	"\rfunction_args\x18\b \x03(\tR\ffunctionArgs\x12>\n" +
	"\x0fcase_conditions\x18\t \x03(\v2\x15.omniql.CaseConditionR\x0ecaseConditions\x12\x1b\n" +
	"\tcase_else\x18\n" +
	" \x01(\tR\bcaseElse\"L\n" +
	"\rCaseCondition\x12\x1c\n" +
	"\tcondition\x18\x01 \x01(\tR\tcondition\x12\x1d\n" +
	"\n" +
	"then_value\x18\x02 \x01(\tR\tthenValue\"\x84\x01\n" +
	"\fSelectColumn\x12\x1e\n" +
	"\n" +
	"expression\x18\x01 \x01(\tR\n" +
	"expression\x12\x14\n" +
	"\x05alias\x18\x02 \x01(\tR\x05alias\x12>\n" +
	"\x0eexpression_obj\x18\x03 \x01(\v2\x17.omniql.FieldExpressionR\rexpressionObj\"\x7f\n" +
	"\n" +
	"JoinClause\x12\x1b\n" +
	"\tjoin_type\x18\x01 \x01(\tR\bjoinType\x12\x14\n" +
	"\x05table\x18\x02 \x01(\tR\x05table\x12\x1d\n" +
	"\n" +
	"left_field\x18\x03 \x01(\tR\tleftField\x12\x1f\n" +
	"\vright_field\x18\x04 \x01(\tR\n" +
	"rightField\"C\n" +
	"\x0fAggregateClause\x12\x1a\n" +
	"\bfunction\x18\x01 \x01(\tR\bfunction\x12\x14\n" +
	"\x05field\x18\x02 \x01(\tR\x05field\"C\n" +
	"\rOrderByClause\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x1c\n" +
	"\tdirection\x18\x02 \x01(\tR\tdirection\"\xc7\x01\n" +
	"\fWindowClause\x12\x1a\n" +
	"\bfunction\x18\x01 \x01(\tR\bfunction\x12\x14\n" +
	"\x05alias\x18\x02 \x01(\tR\x05alias\x12!\n" +
	"\fpartition_by\x18\x03 \x03(\tR\vpartitionBy\x120\n" +
	"\border_by\x18\x04 \x03(\v2\x15.omniql.OrderByClauseR\aorderBy\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\x12\x18\n" +
	"\abuckets\x18\x06 \x01(\x05R\abuckets\"\x9d\x01\n" +
	"\tCTEClause\x12\x19\n" +
	"\bcte_name\x18\x01 \x01(\tR\acteName\x12\x1b\n" +
	"\tcte_query\x18\x02 \x01(\tR\bcteQuery\x12\x1c\n" +
	"\trecursive\x18\x03 \x01(\bR\trecursive\x12:\n" +
	"\x0fadditional_ctes\x18\x04 \x03(\v2\x11.omniql.CTEClauseR\x0eadditionalCtes\"}\n" +
	"\x0eSubqueryClause\x12#\n" +
	"\rsubquery_type\x18\x01 \x01(\tR\fsubqueryType\x12\x14\n" +
	"\x05field\x18\x02 \x01(\tR\x05field\x12\x1a\n" +
	"\bsubquery\x18\x03 \x01(\tR\bsubquery\x12\x14\n" +
	"\x05alias\x18\x04 \x01(\tR\x05alias\"v\n" +
	"\n" +
	"CaseClause\x123\n" +
	"\fwhen_clauses\x18\x01 \x03(\v2\x10.omniql.CaseWhenR\vwhenClauses\x12\x1d\n" +
	"\n" +
	"else_value\x18\x02 \x01(\tR\telseValue\x12\x14\n" +
	"\x05alias\x18\x03 \x01(\tR\x05alias\"G\n" +
	"\bCaseWhen\x12\x1c\n" +
	"\tcondition\x18\x01 \x01(\tR\tcondition\x12\x1d\n" +
	"\n" +
	"then_value\x18\x02 \x01(\tR\tthenValue\"\x99\x01\n" +
	"\fUpsertClause\x12'\n" +
	"\x0fconflict_fields\x18\x01 \x03(\tR\x0econflictFields\x127\n" +
	"\rupdate_fields\x18\x02 \x03(\v2\x12.omniql.QueryFieldR\fupdateFields\x12'\n" +
	"\x0fconflict_action\x18\x03 \x01(\tR\x0econflictAction\";\n" +
	"\rBulkInsertRow\x12*\n" +
	"\x06fields\x18\x01 \x03(\v2\x12.omniql.QueryFieldR\x06fields\"\xad\x01\n" +
	"\x12SetOperationClause\x12%\n" +
	"\x0eoperation_type\x18\x01 \x01(\tR\roperationType\x126\n" +
	"\n" +
	"left_query\x18\x02 \x01(\v2\x17.omniql.RelationalQueryR\tleftQuery\x128\n" +
	"\vright_query\x18\x03 \x01(\v2\x17.omniql.RelationalQueryR\n" +
	"rightQueryB1Z/github.com/omniql-engine/omniql/utilities/protob\x06proto3"

var (
	file_utilities_proto_events_proto_rawDescOnce sync.Once
	file_utilities_proto_events_proto_rawDescData []byte
)

func file_utilities_proto_events_proto_rawDescGZIP() []byte {
	file_utilities_proto_events_proto_rawDescOnce.Do(func() {
		file_utilities_proto_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_utilities_proto_events_proto_rawDesc), len(file_utilities_proto_events_proto_rawDesc)))
	})
	return file_utilities_proto_events_proto_rawDescData
}

var file_utilities_proto_events_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_utilities_proto_events_proto_goTypes = []any{
	(*UniversalQuery)(nil),     // 0: omniql.UniversalQuery
	(*RelationalQuery)(nil),    // 1: omniql.RelationalQuery
	(*DocumentQuery)(nil),      // 2: omniql.DocumentQuery
	(*KeyValueQuery)(nil),      // 3: omniql.KeyValueQuery
	(*KeyValuePair)(nil),       // 4: omniql.KeyValuePair
	(*QueryCondition)(nil),     // 5: omniql.QueryCondition
	(*QueryField)(nil),         // 6: omniql.QueryField
	(*FieldExpression)(nil),    // 7: omniql.FieldExpression
	(*CaseCondition)(nil),      // 8: omniql.CaseCondition
	(*SelectColumn)(nil),       // 9: omniql.SelectColumn
	(*JoinClause)(nil),         // 10: omniql.JoinClause
	(*AggregateClause)(nil),    // 11: omniql.AggregateClause
	(*OrderByClause)(nil),      // 12: omniql.OrderByClause
	(*WindowClause)(nil),       // 13: omniql.WindowClause
	(*CTEClause)(nil),          // 14: omniql.CTEClause
	(*SubqueryClause)(nil),     // 15: omniql.SubqueryClause
	(*CaseClause)(nil),         // 16: omniql.CaseClause
	(*CaseWhen)(nil),           // 17: omniql.CaseWhen
	(*UpsertClause)(nil),       // 18: omniql.UpsertClause
	(*BulkInsertRow)(nil),      // 19: omniql.BulkInsertRow
	(*SetOperationClause)(nil), // 20: omniql.SetOperationClause
}
var file_utilities_proto_events_proto_depIdxs = []int32{
	1,  // 0: omniql.UniversalQuery.relational:type_name -> omniql.RelationalQuery
	2,  // 1: omniql.UniversalQuery.document:type_name -> omniql.DocumentQuery
	3,  // 2: omniql.UniversalQuery.key_value:type_name -> omniql.KeyValueQuery
	5,  // 3: omniql.RelationalQuery.conditions:type_name -> omniql.QueryCondition
	6,  // 4: omniql.RelationalQuery.fields:type_name -> omniql.QueryField
	10, // 5: omniql.RelationalQuery.joins:type_name -> omniql.JoinClause
	11, // 6: omniql.RelationalQuery.aggregate:type_name -> omniql.AggregateClause
	5,  // 7: omniql.RelationalQuery.having:type_name -> omniql.QueryCondition
	12, // 8: omniql.RelationalQuery.order_by:type_name -> omniql.OrderByClause
	13, // 9: omniql.RelationalQuery.window_functions:type_name -> omniql.WindowClause
	14, // 10: omniql.RelationalQuery.cte:type_name -> omniql.CTEClause
	15, // 11: omniql.RelationalQuery.subquery:type_name -> omniql.SubqueryClause
	16, // 12: omniql.RelationalQuery.case_when:type_name -> omniql.CaseClause
	18, // 13: omniql.RelationalQuery.upsert:type_name -> omniql.UpsertClause
	19, // 14: omniql.RelationalQuery.bulk_data:type_name -> omniql.BulkInsertRow
	20, // 15: omniql.RelationalQuery.set_operation:type_name -> omniql.SetOperationClause
	9,  // 16: omniql.RelationalQuery.select_columns:type_name -> omniql.SelectColumn
	5,  // 17: omniql.DocumentQuery.conditions:type_name -> omniql.QueryCondition
	6,  // 18: omniql.DocumentQuery.fields:type_name -> omniql.QueryField
	10, // 19: omniql.DocumentQuery.joins:type_name -> omniql.JoinClause
	11, // 20: omniql.DocumentQuery.aggregate:type_name -> omniql.AggregateClause
	12, // 21: omniql.DocumentQuery.order_by:type_name -> omniql.OrderByClause
	13, // 22: omniql.DocumentQuery.window_functions:type_name -> omniql.WindowClause
	16, // 23: omniql.DocumentQuery.case_when:type_name -> omniql.CaseClause
	18, // 24: omniql.DocumentQuery.upsert:type_name -> omniql.UpsertClause
	19, // 25: omniql.DocumentQuery.bulk_data:type_name -> omniql.BulkInsertRow
	20, // 26: omniql.DocumentQuery.set_operation:type_name -> omniql.SetOperationClause
	9,  // 27: omniql.DocumentQuery.select_columns:type_name -> omniql.SelectColumn
	5,  // 28: omniql.DocumentQuery.having:type_name -> omniql.QueryCondition
	4,  // 29: omniql.KeyValueQuery.bulk_pairs:type_name -> omniql.KeyValuePair
	7,  // 30: omniql.QueryField.expression:type_name -> omniql.FieldExpression
	8,  // 31: omniql.FieldExpression.case_conditions:type_name -> omniql.CaseCondition
	7,  // 32: omniql.SelectColumn.expression_obj:type_name -> omniql.FieldExpression
	12, // 33: omniql.WindowClause.order_by:type_name -> omniql.OrderByClause
	14, // 34: omniql.CTEClause.additional_ctes:type_name -> omniql.CTEClause
	17, // 35: omniql.CaseClause.when_clauses:type_name -> omniql.CaseWhen
	6,  // 36: omniql.UpsertClause.update_fields:type_name -> omniql.QueryField
	6,  // 37: omniql.BulkInsertRow.fields:type_name -> omniql.QueryField
	1,  // 38: omniql.SetOperationClause.left_query:type_name -> omniql.RelationalQuery
	1,  // 39: omniql.SetOperationClause.right_query:type_name -> omniql.RelationalQuery
	40, // [40:40] is the sub-list for method output_type
	40, // [40:40] is the sub-list for method input_type
	40, // [40:40] is the sub-list for extension type_name
	40, // [40:40] is the sub-list for extension extendee
	0,  // [0:40] is the sub-list for field type_name
}

func init() { file_utilities_proto_events_proto_init() }
func file_utilities_proto_events_proto_init() {
	if File_utilities_proto_events_proto != nil {
		return
	}
	file_utilities_proto_events_proto_msgTypes[0].OneofWrappers = []any{
		(*UniversalQuery_Relational)(nil),
		(*UniversalQuery_Document)(nil),
		(*UniversalQuery_KeyValue)(nil),
	}
	file_utilities_proto_events_proto_msgTypes[6].OneofWrappers = []any{
		(*QueryField_LiteralValue)(nil),
		(*QueryField_Expression)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_utilities_proto_events_proto_rawDesc), len(file_utilities_proto_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_utilities_proto_events_proto_goTypes,
		DependencyIndexes: file_utilities_proto_events_proto_depIdxs,
		MessageInfos:      file_utilities_proto_events_proto_msgTypes,
	}.Build()
	File_utilities_proto_events_proto = out.File
	file_utilities_proto_events_proto_goTypes = nil
	file_utilities_proto_events_proto_depIdxs = nil
}
