// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: utilities/proto/events.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UniversalQuery struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to QueryType:
	//
	//	*UniversalQuery_Relational
	//	*UniversalQuery_Document
	//	*UniversalQuery_KeyValue
	QueryType     isUniversalQuery_QueryType `protobuf_oneof:"query_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UniversalQuery) Reset() {
	*x = UniversalQuery{}
	mi := &file_utilities_proto_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UniversalQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniversalQuery) ProtoMessage() {}

func (x *UniversalQuery) ProtoReflect() protoreflect.Message {
	mi := &file_utilities_proto_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniversalQuery.ProtoReflect.Descriptor instead.
func (*UniversalQuery) Descriptor() ([]byte, []int) {
	return file_utilities_proto_events_proto_rawDescGZIP(), []int{0}
}

func (x *UniversalQuery) GetQueryType() isUniversalQuery_QueryType {
	if x != nil {
		return x.QueryType
	}
	return nil
}

func (x *UniversalQuery) GetRelational() *RelationalQuery {
	if x != nil {
		if x, ok := x.QueryType.(*UniversalQuery_Relational); ok {
			return x.Relational
		}
	}
	return nil
}

func (x *UniversalQuery) GetDocument() *DocumentQuery {
	if x != nil {
		if x, ok := x.QueryType.(*UniversalQuery_Document); ok {
			return x.Document
		}
	}
	return nil
}

func (x *UniversalQuery) GetKeyValue() *KeyValueQuery {
	if x != nil {
		if x, ok := x.QueryType.(*UniversalQuery_KeyValue); ok {
			return x.KeyValue
		}
	}
	return nil
}

type isUniversalQuery_QueryType interface {
	isUniversalQuery_QueryType()
}

type UniversalQuery_Relational struct {
	Relational *RelationalQuery `protobuf:"bytes,1,opt,name=relational,proto3,oneof"` // PostgreSQL, MySQL, SQLite
}

type UniversalQuery_Document struct {
	Document *DocumentQuery `protobuf:"bytes,2,opt,name=document,proto3,oneof"` // MongoDB
}

type UniversalQuery_KeyValue struct {
	KeyValue *KeyValueQuery `protobuf:"bytes,3,opt,name=key_value,json=keyValue,proto3,oneof"` // Redis
}

func (*UniversalQuery_Relational) isUniversalQuery_QueryType() {}

func (*UniversalQuery_Document) isUniversalQuery_QueryType() {}

func (*UniversalQuery_KeyValue) isUniversalQuery_QueryType() {}

type Expression struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Type     string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // BINARY, FUNCTION, CASEWHEN, FIELD, LITERAL, WINDOW
	Position int32                  `protobuf:"varint,2,opt,name=position,proto3" json:"position,omitempty"`
	// For leaf nodes (FIELD, LITERAL)
	Value string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	// For BINARY expressions
	Left     *Expression `protobuf:"bytes,4,opt,name=left,proto3" json:"left,omitempty"`
	Operator string      `protobuf:"bytes,5,opt,name=operator,proto3" json:"operator,omitempty"`
	Right    *Expression `protobuf:"bytes,6,opt,name=right,proto3" json:"right,omitempty"`
	// For FUNCTION calls
	FunctionName string        `protobuf:"bytes,7,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"`
	FunctionArgs []*Expression `protobuf:"bytes,8,rep,name=function_args,json=functionArgs,proto3" json:"function_args,omitempty"`
	// For CASEWHEN
	CaseConditions []*CaseCondition `protobuf:"bytes,9,rep,name=case_conditions,json=caseConditions,proto3" json:"case_conditions,omitempty"`
	CaseElse       *Expression      `protobuf:"bytes,10,opt,name=case_else,json=caseElse,proto3" json:"case_else,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Expression) Reset() {
	*x = Expression{}
	mi := &file_utilities_proto_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Expression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expression) ProtoMessage() {}

func (x *Expression) ProtoReflect() protoreflect.Message {
	mi := &file_utilities_proto_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expression.ProtoReflect.Descriptor instead.
func (*Expression) Descriptor() ([]byte, []int) {
	return file_utilities_proto_events_proto_rawDescGZIP(), []int{1}
}

func (x *Expression) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Expression) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *Expression) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Expression) GetLeft() *Expression {
	if x != nil {
		return x.Left
	}
	return nil
}

func (x *Expression) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *Expression) GetRight() *Expression {
	if x != nil {
		return x.Right
	}
	return nil
}

func (x *Expression) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

func (x *Expression) GetFunctionArgs() []*Expression {
	if x != nil {
		return x.FunctionArgs
	}
	return nil
}

func (x *Expression) GetCaseConditions() []*CaseCondition {
	if x != nil {
		return x.CaseConditions
	}
	return nil
}

func (x *Expression) GetCaseElse() *Expression {
	if x != nil {
		return x.CaseElse
	}
	return nil
}

type QueryCondition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FieldExpr     *Expression            `protobuf:"bytes,1,opt,name=field_expr,json=fieldExpr,proto3" json:"field_expr,omitempty"`    // Left side
	Operator      string                 `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`                       // =, !=, >, <, IN, BETWEEN, etc.
	ValueExpr     *Expression            `protobuf:"bytes,3,opt,name=value_expr,json=valueExpr,proto3" json:"value_expr,omitempty"`    // Right side
	Value2Expr    *Expression            `protobuf:"bytes,4,opt,name=value2_expr,json=value2Expr,proto3" json:"value2_expr,omitempty"` // For BETWEEN second value
	ValuesExpr    []*Expression          `protobuf:"bytes,5,rep,name=values_expr,json=valuesExpr,proto3" json:"values_expr,omitempty"` // For IN operator values
	Logic         string                 `protobuf:"bytes,6,opt,name=logic,proto3" json:"logic,omitempty"`                             // AND, OR
	Nested        []*QueryCondition      `protobuf:"bytes,7,rep,name=nested,proto3" json:"nested,omitempty"`                           // For parentheses grouping
	Position      int32                  `protobuf:"varint,8,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryCondition) Reset() {
	*x = QueryCondition{}
	mi := &file_utilities_proto_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryCondition) ProtoMessage() {}

func (x *QueryCondition) ProtoReflect() protoreflect.Message {
	mi := &file_utilities_proto_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryCondition.ProtoReflect.Descriptor instead.
func (*QueryCondition) Descriptor() ([]byte, []int) {
	return file_utilities_proto_events_proto_rawDescGZIP(), []int{2}
}

func (x *QueryCondition) GetFieldExpr() *Expression {
	if x != nil {
		return x.FieldExpr
	}
	return nil
}

func (x *QueryCondition) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *QueryCondition) GetValueExpr() *Expression {
	if x != nil {
		return x.ValueExpr
	}
	return nil
}

func (x *QueryCondition) GetValue2Expr() *Expression {
	if x != nil {
		return x.Value2Expr
	}
	return nil
}

func (x *QueryCondition) GetValuesExpr() []*Expression {
	if x != nil {
		return x.ValuesExpr
	}
	return nil
}

func (x *QueryCondition) GetLogic() string {
	if x != nil {
		return x.Logic
	}
	return ""
}

func (x *QueryCondition) GetNested() []*QueryCondition {
	if x != nil {
		return x.Nested
	}
	return nil
}

func (x *QueryCondition) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

type CaseCondition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Condition     *QueryCondition        `protobuf:"bytes,1,opt,name=condition,proto3" json:"condition,omitempty"`               // WHEN condition
	ThenExpr      *Expression            `protobuf:"bytes,2,opt,name=then_expr,json=thenExpr,proto3" json:"then_expr,omitempty"` // THEN value
	Position      int32                  `protobuf:"varint,3,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaseCondition) Reset() {
	*x = CaseCondition{}
	mi := &file_utilities_proto_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaseCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaseCondition) ProtoMessage() {}

func (x *CaseCondition) ProtoReflect() protoreflect.Message {
	mi := &file_utilities_proto_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaseCondition.ProtoReflect.Descriptor instead.
func (*CaseCondition) Descriptor() ([]byte, []int) {
	return file_utilities_proto_events_proto_rawDescGZIP(), []int{3}
}

func (x *CaseCondition) GetCondition() *QueryCondition {
	if x != nil {
		return x.Condition
	}
	return nil
}

func (x *CaseCondition) GetThenExpr() *Expression {
	if x != nil {
		return x.ThenExpr
	}
	return nil
}

func (x *CaseCondition) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

type QueryField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NameExpr      *Expression            `protobuf:"bytes,1,opt,name=name_expr,json=nameExpr,proto3" json:"name_expr,omitempty"`    // Field name
	ValueExpr     *Expression            `protobuf:"bytes,2,opt,name=value_expr,json=valueExpr,proto3" json:"value_expr,omitempty"` // Field value
	Constraints   []string               `protobuf:"bytes,3,rep,name=constraints,proto3" json:"constraints,omitempty"`              // DDL: UNIQUE, NOT_NULL, PRIMARY_KEY
	Position      int32                  `protobuf:"varint,4,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryField) Reset() {
	*x = QueryField{}
	mi := &file_utilities_proto_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryField) ProtoMessage() {}

func (x *QueryField) ProtoReflect() protoreflect.Message {
	mi := &file_utilities_proto_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryField.ProtoReflect.Descriptor instead.
func (*QueryField) Descriptor() ([]byte, []int) {
	return file_utilities_proto_events_proto_rawDescGZIP(), []int{4}
}

func (x *QueryField) GetNameExpr() *Expression {
	if x != nil {
		return x.NameExpr
	}
	return nil
}

func (x *QueryField) GetValueExpr() *Expression {
	if x != nil {
		return x.ValueExpr
	}
	return nil
}

func (x *QueryField) GetConstraints() []string {
	if x != nil {
		return x.Constraints
	}
	return nil
}

func (x *QueryField) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

type SelectColumn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExpressionObj *Expression            `protobuf:"bytes,1,opt,name=expression_obj,json=expressionObj,proto3" json:"expression_obj,omitempty"` // The expression
	Alias         string                 `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`                                      // Optional alias
	Position      int32                  `protobuf:"varint,3,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectColumn) Reset() {
	*x = SelectColumn{}
	mi := &file_utilities_proto_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectColumn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectColumn) ProtoMessage() {}

func (x *SelectColumn) ProtoReflect() protoreflect.Message {
	mi := &file_utilities_proto_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectColumn.ProtoReflect.Descriptor instead.
func (*SelectColumn) Descriptor() ([]byte, []int) {
	return file_utilities_proto_events_proto_rawDescGZIP(), []int{5}
}

func (x *SelectColumn) GetExpressionObj() *Expression {
	if x != nil {
		return x.ExpressionObj
	}
	return nil
}

func (x *SelectColumn) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *SelectColumn) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

type RelationalQuery struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Operation        string                 `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	Table            string                 `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	Conditions       []*QueryCondition      `protobuf:"bytes,3,rep,name=conditions,proto3" json:"conditions,omitempty"`
	Fields           []*QueryField          `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty"`
	Limit            int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset           int32                  `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`
	Distinct         bool                   `protobuf:"varint,7,opt,name=distinct,proto3" json:"distinct,omitempty"`
	TransactionId    string                 `protobuf:"bytes,8,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Joins            []*JoinClause          `protobuf:"bytes,9,rep,name=joins,proto3" json:"joins,omitempty"`
	Aggregate        *AggregateClause       `protobuf:"bytes,10,opt,name=aggregate,proto3" json:"aggregate,omitempty"`
	GroupBy          []*Expression          `protobuf:"bytes,11,rep,name=group_by,json=groupBy,proto3" json:"group_by,omitempty"` // 100% TrueAST
	Having           []*QueryCondition      `protobuf:"bytes,12,rep,name=having,proto3" json:"having,omitempty"`
	OrderBy          []*OrderByClause       `protobuf:"bytes,13,rep,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	SavepointName    string                 `protobuf:"bytes,14,opt,name=savepoint_name,json=savepointName,proto3" json:"savepoint_name,omitempty"`
	Permissions      []string               `protobuf:"bytes,15,rep,name=permissions,proto3" json:"permissions,omitempty"`
	PermissionTarget string                 `protobuf:"bytes,16,opt,name=permission_target,json=permissionTarget,proto3" json:"permission_target,omitempty"`
	RoleName         string                 `protobuf:"bytes,17,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	WindowFunctions  []*WindowClause        `protobuf:"bytes,18,rep,name=window_functions,json=windowFunctions,proto3" json:"window_functions,omitempty"`
	Cte              *CTEClause             `protobuf:"bytes,19,opt,name=cte,proto3" json:"cte,omitempty"`
	Subquery         *SubqueryClause        `protobuf:"bytes,20,opt,name=subquery,proto3" json:"subquery,omitempty"`
	Pattern          string                 `protobuf:"bytes,21,opt,name=pattern,proto3" json:"pattern,omitempty"`
	IsolationLevel   string                 `protobuf:"bytes,22,opt,name=isolation_level,json=isolationLevel,proto3" json:"isolation_level,omitempty"`
	ReadOnly         bool                   `protobuf:"varint,23,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	Upsert           *UpsertClause          `protobuf:"bytes,24,opt,name=upsert,proto3" json:"upsert,omitempty"`
	BulkData         []*BulkInsertRow       `protobuf:"bytes,25,rep,name=bulk_data,json=bulkData,proto3" json:"bulk_data,omitempty"`
	ViewName         string                 `protobuf:"bytes,26,opt,name=view_name,json=viewName,proto3" json:"view_name,omitempty"`
	ViewQuery        *RelationalQuery       `protobuf:"bytes,27,opt,name=view_query,json=viewQuery,proto3" json:"view_query,omitempty"` // 100% TrueAST
	DatabaseName     string                 `protobuf:"bytes,28,opt,name=database_name,json=databaseName,proto3" json:"database_name,omitempty"`
	NewName          string                 `protobuf:"bytes,29,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
	UserName         string                 `protobuf:"bytes,30,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Password         string                 `protobuf:"bytes,31,opt,name=password,proto3" json:"password,omitempty"`
	UserRoles        []string               `protobuf:"bytes,32,rep,name=user_roles,json=userRoles,proto3" json:"user_roles,omitempty"`
	SetOperation     *SetOperationClause    `protobuf:"bytes,33,opt,name=set_operation,json=setOperation,proto3" json:"set_operation,omitempty"`
	Columns          []*Expression          `protobuf:"bytes,34,rep,name=columns,proto3" json:"columns,omitempty"` // 100% TrueAST
	SelectColumns    []*SelectColumn        `protobuf:"bytes,35,rep,name=select_columns,json=selectColumns,proto3" json:"select_columns,omitempty"`
	SessionId        string                 `protobuf:"bytes,36,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Sql              string                 `protobuf:"bytes,37,opt,name=sql,proto3" json:"sql,omitempty"`
	AlterAction      string                 `protobuf:"bytes,38,opt,name=alter_action,json=alterAction,proto3" json:"alter_action,omitempty"` // ADD_COLUMN, DROP_COLUMN, RENAME_COLUMN
	// PostgreSQL-specific DDL
	SequenceName      string   `protobuf:"bytes,39,opt,name=sequence_name,json=sequenceName,proto3" json:"sequence_name,omitempty"`
	SequenceStart     int64    `protobuf:"varint,40,opt,name=sequence_start,json=sequenceStart,proto3" json:"sequence_start,omitempty"`
	SequenceIncrement int64    `protobuf:"varint,41,opt,name=sequence_increment,json=sequenceIncrement,proto3" json:"sequence_increment,omitempty"`
	SequenceMin       int64    `protobuf:"varint,42,opt,name=sequence_min,json=sequenceMin,proto3" json:"sequence_min,omitempty"`
	SequenceMax       int64    `protobuf:"varint,43,opt,name=sequence_max,json=sequenceMax,proto3" json:"sequence_max,omitempty"`
	SequenceCache     int64    `protobuf:"varint,44,opt,name=sequence_cache,json=sequenceCache,proto3" json:"sequence_cache,omitempty"`
	SequenceCycle     bool     `protobuf:"varint,45,opt,name=sequence_cycle,json=sequenceCycle,proto3" json:"sequence_cycle,omitempty"`
	SequenceRestart   int64    `protobuf:"varint,46,opt,name=sequence_restart,json=sequenceRestart,proto3" json:"sequence_restart,omitempty"`
	ExtensionName     string   `protobuf:"bytes,47,opt,name=extension_name,json=extensionName,proto3" json:"extension_name,omitempty"`
	SchemaName        string   `protobuf:"bytes,48,opt,name=schema_name,json=schemaName,proto3" json:"schema_name,omitempty"`
	SchemaOwner       string   `protobuf:"bytes,49,opt,name=schema_owner,json=schemaOwner,proto3" json:"schema_owner,omitempty"`
	TypeName          string   `protobuf:"bytes,50,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	TypeKind          string   `protobuf:"bytes,51,opt,name=type_kind,json=typeKind,proto3" json:"type_kind,omitempty"`
	EnumValues        []string `protobuf:"bytes,52,rep,name=enum_values,json=enumValues,proto3" json:"enum_values,omitempty"`
	EnumValue         string   `protobuf:"bytes,53,opt,name=enum_value,json=enumValue,proto3" json:"enum_value,omitempty"`
	NewEnumValue      string   `protobuf:"bytes,54,opt,name=new_enum_value,json=newEnumValue,proto3" json:"new_enum_value,omitempty"`
	DomainName        string   `protobuf:"bytes,55,opt,name=domain_name,json=domainName,proto3" json:"domain_name,omitempty"`
	DomainType        string   `protobuf:"bytes,56,opt,name=domain_type,json=domainType,proto3" json:"domain_type,omitempty"`
	DomainDefault     string   `protobuf:"bytes,57,opt,name=domain_default,json=domainDefault,proto3" json:"domain_default,omitempty"`
	DomainConstraint  string   `protobuf:"bytes,58,opt,name=domain_constraint,json=domainConstraint,proto3" json:"domain_constraint,omitempty"`
	FuncName          string   `protobuf:"bytes,59,opt,name=func_name,json=funcName,proto3" json:"func_name,omitempty"`
	FuncBody          string   `protobuf:"bytes,60,opt,name=func_body,json=funcBody,proto3" json:"func_body,omitempty"`
	FuncArgs          []string `protobuf:"bytes,61,rep,name=func_args,json=funcArgs,proto3" json:"func_args,omitempty"`
	FuncReturns       string   `protobuf:"bytes,62,opt,name=func_returns,json=funcReturns,proto3" json:"func_returns,omitempty"`
	FuncLanguage      string   `protobuf:"bytes,63,opt,name=func_language,json=funcLanguage,proto3" json:"func_language,omitempty"`
	FuncOwner         string   `protobuf:"bytes,64,opt,name=func_owner,json=funcOwner,proto3" json:"func_owner,omitempty"`
	TriggerName       string   `protobuf:"bytes,65,opt,name=trigger_name,json=triggerName,proto3" json:"trigger_name,omitempty"`
	TriggerTiming     string   `protobuf:"bytes,66,opt,name=trigger_timing,json=triggerTiming,proto3" json:"trigger_timing,omitempty"`
	TriggerEvents     string   `protobuf:"bytes,67,opt,name=trigger_events,json=triggerEvents,proto3" json:"trigger_events,omitempty"`
	TriggerForEach    string   `protobuf:"bytes,68,opt,name=trigger_for_each,json=triggerForEach,proto3" json:"trigger_for_each,omitempty"`
	PolicyName        string   `protobuf:"bytes,69,opt,name=policy_name,json=policyName,proto3" json:"policy_name,omitempty"`
	PolicyFor         string   `protobuf:"bytes,70,opt,name=policy_for,json=policyFor,proto3" json:"policy_for,omitempty"`
	PolicyTo          string   `protobuf:"bytes,71,opt,name=policy_to,json=policyTo,proto3" json:"policy_to,omitempty"`
	PolicyUsing       string   `protobuf:"bytes,72,opt,name=policy_using,json=policyUsing,proto3" json:"policy_using,omitempty"`
	PolicyCheck       string   `protobuf:"bytes,73,opt,name=policy_check,json=policyCheck,proto3" json:"policy_check,omitempty"`
	RuleName          string   `protobuf:"bytes,74,opt,name=rule_name,json=ruleName,proto3" json:"rule_name,omitempty"`
	RuleEvent         string   `protobuf:"bytes,75,opt,name=rule_event,json=ruleEvent,proto3" json:"rule_event,omitempty"`
	RuleAction        string   `protobuf:"bytes,76,opt,name=rule_action,json=ruleAction,proto3" json:"rule_action,omitempty"`
	CommentTarget     string   `protobuf:"bytes,77,opt,name=comment_target,json=commentTarget,proto3" json:"comment_target,omitempty"`
	CommentText       string   `protobuf:"bytes,78,opt,name=comment_text,json=commentText,proto3" json:"comment_text,omitempty"`
	Cascade           bool     `protobuf:"varint,79,opt,name=cascade,proto3" json:"cascade,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RelationalQuery) Reset() {
	*x = RelationalQuery{}
	mi := &file_utilities_proto_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationalQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationalQuery) ProtoMessage() {}

func (x *RelationalQuery) ProtoReflect() protoreflect.Message {
	mi := &file_utilities_proto_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationalQuery.ProtoReflect.Descriptor instead.
func (*RelationalQuery) Descriptor() ([]byte, []int) {
	return file_utilities_proto_events_proto_rawDescGZIP(), []int{6}
}

func (x *RelationalQuery) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *RelationalQuery) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *RelationalQuery) GetConditions() []*QueryCondition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *RelationalQuery) GetFields() []*QueryField {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *RelationalQuery) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *RelationalQuery) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *RelationalQuery) GetDistinct() bool {
	if x != nil {
		return x.Distinct
	}
	return false
}

func (x *RelationalQuery) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *RelationalQuery) GetJoins() []*JoinClause {
	if x != nil {
		return x.Joins
	}
	return nil
}

func (x *RelationalQuery) GetAggregate() *AggregateClause {
	if x != nil {
		return x.Aggregate
	}
	return nil
}

func (x *RelationalQuery) GetGroupBy() []*Expression {
	if x != nil {
		return x.GroupBy
	}
	return nil
}

func (x *RelationalQuery) GetHaving() []*QueryCondition {
	if x != nil {
		return x.Having
	}
	return nil
}

func (x *RelationalQuery) GetOrderBy() []*OrderByClause {
	if x != nil {
		return x.OrderBy
	}
	return nil
}

func (x *RelationalQuery) GetSavepointName() string {
	if x != nil {
		return x.SavepointName
	}
	return ""
}

func (x *RelationalQuery) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *RelationalQuery) GetPermissionTarget() string {
	if x != nil {
		return x.PermissionTarget
	}
	return ""
}

func (x *RelationalQuery) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *RelationalQuery) GetWindowFunctions() []*WindowClause {
	if x != nil {
		return x.WindowFunctions
	}
	return nil
}

func (x *RelationalQuery) GetCte() *CTEClause {
	if x != nil {
		return x.Cte
	}
	return nil
}

func (x *RelationalQuery) GetSubquery() *SubqueryClause {
	if x != nil {
		return x.Subquery
	}
	return nil
}

func (x *RelationalQuery) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *RelationalQuery) GetIsolationLevel() string {
	if x != nil {
		return x.IsolationLevel
	}
	return ""
}

func (x *RelationalQuery) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

func (x *RelationalQuery) GetUpsert() *UpsertClause {
	if x != nil {
		return x.Upsert
	}
	return nil
}

func (x *RelationalQuery) GetBulkData() []*BulkInsertRow {
	if x != nil {
		return x.BulkData
	}
	return nil
}

func (x *RelationalQuery) GetViewName() string {
	if x != nil {
		return x.ViewName
	}
	return ""
}

func (x *RelationalQuery) GetViewQuery() *RelationalQuery {
	if x != nil {
		return x.ViewQuery
	}
	return nil
}

func (x *RelationalQuery) GetDatabaseName() string {
	if x != nil {
		return x.DatabaseName
	}
	return ""
}

func (x *RelationalQuery) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

func (x *RelationalQuery) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *RelationalQuery) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RelationalQuery) GetUserRoles() []string {
	if x != nil {
		return x.UserRoles
	}
	return nil
}

func (x *RelationalQuery) GetSetOperation() *SetOperationClause {
	if x != nil {
		return x.SetOperation
	}
	return nil
}

func (x *RelationalQuery) GetColumns() []*Expression {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *RelationalQuery) GetSelectColumns() []*SelectColumn {
	if x != nil {
		return x.SelectColumns
	}
	return nil
}

func (x *RelationalQuery) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RelationalQuery) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *RelationalQuery) GetAlterAction() string {
	if x != nil {
		return x.AlterAction
	}
	return ""
}

func (x *RelationalQuery) GetSequenceName() string {
	if x != nil {
		return x.SequenceName
	}
	return ""
}

func (x *RelationalQuery) GetSequenceStart() int64 {
	if x != nil {
		return x.SequenceStart
	}
	return 0
}

func (x *RelationalQuery) GetSequenceIncrement() int64 {
	if x != nil {
		return x.SequenceIncrement
	}
	return 0
}

func (x *RelationalQuery) GetSequenceMin() int64 {
	if x != nil {
		return x.SequenceMin
	}
	return 0
}

func (x *RelationalQuery) GetSequenceMax() int64 {
	if x != nil {
		return x.SequenceMax
	}
	return 0
}

func (x *RelationalQuery) GetSequenceCache() int64 {
	if x != nil {
		return x.SequenceCache
	}
	return 0
}

func (x *RelationalQuery) GetSequenceCycle() bool {
	if x != nil {
		return x.SequenceCycle
	}
	return false
}

func (x *RelationalQuery) GetSequenceRestart() int64 {
	if x != nil {
		return x.SequenceRestart
	}
	return 0
}

func (x *RelationalQuery) GetExtensionName() string {
	if x != nil {
		return x.ExtensionName
	}
	return ""
}

func (x *RelationalQuery) GetSchemaName() string {
	if x != nil {
		return x.SchemaName
	}
	return ""
}

func (x *RelationalQuery) GetSchemaOwner() string {
	if x != nil {
		return x.SchemaOwner
	}
	return ""
}

func (x *RelationalQuery) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *RelationalQuery) GetTypeKind() string {
	if x != nil {
		return x.TypeKind
	}
	return ""
}

func (x *RelationalQuery) GetEnumValues() []string {
	if x != nil {
		return x.EnumValues
	}
	return nil
}

func (x *RelationalQuery) GetEnumValue() string {
	if x != nil {
		return x.EnumValue
	}
	return ""
}

func (x *RelationalQuery) GetNewEnumValue() string {
	if x != nil {
		return x.NewEnumValue
	}
	return ""
}

func (x *RelationalQuery) GetDomainName() string {
	if x != nil {
		return x.DomainName
	}
	return ""
}

func (x *RelationalQuery) GetDomainType() string {
	if x != nil {
		return x.DomainType
	}
	return ""
}

func (x *RelationalQuery) GetDomainDefault() string {
	if x != nil {
		return x.DomainDefault
	}
	return ""
}

func (x *RelationalQuery) GetDomainConstraint() string {
	if x != nil {
		return x.DomainConstraint
	}
	return ""
}

func (x *RelationalQuery) GetFuncName() string {
	if x != nil {
		return x.FuncName
	}
	return ""
}

func (x *RelationalQuery) GetFuncBody() string {
	if x != nil {
		return x.FuncBody
	}
	return ""
}

func (x *RelationalQuery) GetFuncArgs() []string {
	if x != nil {
		return x.FuncArgs
	}
	return nil
}

func (x *RelationalQuery) GetFuncReturns() string {
	if x != nil {
		return x.FuncReturns
	}
	return ""
}

func (x *RelationalQuery) GetFuncLanguage() string {
	if x != nil {
		return x.FuncLanguage
	}
	return ""
}

func (x *RelationalQuery) GetFuncOwner() string {
	if x != nil {
		return x.FuncOwner
	}
	return ""
}

func (x *RelationalQuery) GetTriggerName() string {
	if x != nil {
		return x.TriggerName
	}
	return ""
}

func (x *RelationalQuery) GetTriggerTiming() string {
	if x != nil {
		return x.TriggerTiming
	}
	return ""
}

func (x *RelationalQuery) GetTriggerEvents() string {
	if x != nil {
		return x.TriggerEvents
	}
	return ""
}

func (x *RelationalQuery) GetTriggerForEach() string {
	if x != nil {
		return x.TriggerForEach
	}
	return ""
}

func (x *RelationalQuery) GetPolicyName() string {
	if x != nil {
		return x.PolicyName
	}
	return ""
}

func (x *RelationalQuery) GetPolicyFor() string {
	if x != nil {
		return x.PolicyFor
	}
	return ""
}

func (x *RelationalQuery) GetPolicyTo() string {
	if x != nil {
		return x.PolicyTo
	}
	return ""
}

func (x *RelationalQuery) GetPolicyUsing() string {
	if x != nil {
		return x.PolicyUsing
	}
	return ""
}

func (x *RelationalQuery) GetPolicyCheck() string {
	if x != nil {
		return x.PolicyCheck
	}
	return ""
}

func (x *RelationalQuery) GetRuleName() string {
	if x != nil {
		return x.RuleName
	}
	return ""
}

func (x *RelationalQuery) GetRuleEvent() string {
	if x != nil {
		return x.RuleEvent
	}
	return ""
}

func (x *RelationalQuery) GetRuleAction() string {
	if x != nil {
		return x.RuleAction
	}
	return ""
}

func (x *RelationalQuery) GetCommentTarget() string {
	if x != nil {
		return x.CommentTarget
	}
	return ""
}

func (x *RelationalQuery) GetCommentText() string {
	if x != nil {
		return x.CommentText
	}
	return ""
}

func (x *RelationalQuery) GetCascade() bool {
	if x != nil {
		return x.Cascade
	}
	return false
}

type DocumentQuery struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Operation        string                 `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	Collection       string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	Conditions       []*QueryCondition      `protobuf:"bytes,3,rep,name=conditions,proto3" json:"conditions,omitempty"`
	Fields           []*QueryField          `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty"`
	Limit            int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Skip             int32                  `protobuf:"varint,6,opt,name=skip,proto3" json:"skip,omitempty"`
	Joins            []*JoinClause          `protobuf:"bytes,7,rep,name=joins,proto3" json:"joins,omitempty"`
	Aggregate        *AggregateClause       `protobuf:"bytes,8,opt,name=aggregate,proto3" json:"aggregate,omitempty"`
	GroupBy          []*Expression          `protobuf:"bytes,9,rep,name=group_by,json=groupBy,proto3" json:"group_by,omitempty"` // 100% TrueAST
	OrderBy          []*OrderByClause       `protobuf:"bytes,10,rep,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	SavepointName    string                 `protobuf:"bytes,11,opt,name=savepoint_name,json=savepointName,proto3" json:"savepoint_name,omitempty"`
	Permissions      []string               `protobuf:"bytes,12,rep,name=permissions,proto3" json:"permissions,omitempty"`
	PermissionTarget string                 `protobuf:"bytes,13,opt,name=permission_target,json=permissionTarget,proto3" json:"permission_target,omitempty"`
	RoleName         string                 `protobuf:"bytes,14,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	WindowFunctions  []*WindowClause        `protobuf:"bytes,15,rep,name=window_functions,json=windowFunctions,proto3" json:"window_functions,omitempty"`
	Pattern          string                 `protobuf:"bytes,16,opt,name=pattern,proto3" json:"pattern,omitempty"`
	IsolationLevel   string                 `protobuf:"bytes,17,opt,name=isolation_level,json=isolationLevel,proto3" json:"isolation_level,omitempty"`
	ReadOnly         bool                   `protobuf:"varint,18,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	Upsert           *UpsertClause          `protobuf:"bytes,19,opt,name=upsert,proto3" json:"upsert,omitempty"`
	BulkData         []*BulkInsertRow       `protobuf:"bytes,20,rep,name=bulk_data,json=bulkData,proto3" json:"bulk_data,omitempty"`
	ViewName         string                 `protobuf:"bytes,21,opt,name=view_name,json=viewName,proto3" json:"view_name,omitempty"`
	ViewQuery        *DocumentQuery         `protobuf:"bytes,22,opt,name=view_query,json=viewQuery,proto3" json:"view_query,omitempty"` // 100% TrueAST
	DatabaseName     string                 `protobuf:"bytes,23,opt,name=database_name,json=databaseName,proto3" json:"database_name,omitempty"`
	UserName         string                 `protobuf:"bytes,24,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Password         string                 `protobuf:"bytes,25,opt,name=password,proto3" json:"password,omitempty"`
	UserRoles        []string               `protobuf:"bytes,26,rep,name=user_roles,json=userRoles,proto3" json:"user_roles,omitempty"`
	NewName          string                 `protobuf:"bytes,27,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
	SetOperation     *SetOperationClause    `protobuf:"bytes,28,opt,name=set_operation,json=setOperation,proto3" json:"set_operation,omitempty"`
	Columns          []*Expression          `protobuf:"bytes,29,rep,name=columns,proto3" json:"columns,omitempty"` // 100% TrueAST
	SelectColumns    []*SelectColumn        `protobuf:"bytes,30,rep,name=select_columns,json=selectColumns,proto3" json:"select_columns,omitempty"`
	SessionId        string                 `protobuf:"bytes,31,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Having           []*QueryCondition      `protobuf:"bytes,32,rep,name=having,proto3" json:"having,omitempty"`
	Distinct         bool                   `protobuf:"varint,33,opt,name=distinct,proto3" json:"distinct,omitempty"`
	Query            string                 `protobuf:"bytes,34,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DocumentQuery) Reset() {
	*x = DocumentQuery{}
	mi := &file_utilities_proto_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentQuery) ProtoMessage() {}

func (x *DocumentQuery) ProtoReflect() protoreflect.Message {
	mi := &file_utilities_proto_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentQuery.ProtoReflect.Descriptor instead.
func (*DocumentQuery) Descriptor() ([]byte, []int) {
	return file_utilities_proto_events_proto_rawDescGZIP(), []int{7}
}

func (x *DocumentQuery) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *DocumentQuery) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *DocumentQuery) GetConditions() []*QueryCondition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *DocumentQuery) GetFields() []*QueryField {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *DocumentQuery) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *DocumentQuery) GetSkip() int32 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *DocumentQuery) GetJoins() []*JoinClause {
	if x != nil {
		return x.Joins
	}
	return nil
}

func (x *DocumentQuery) GetAggregate() *AggregateClause {
	if x != nil {
		return x.Aggregate
	}
	return nil
}

func (x *DocumentQuery) GetGroupBy() []*Expression {
	if x != nil {
		return x.GroupBy
	}
	return nil
}

func (x *DocumentQuery) GetOrderBy() []*OrderByClause {
	if x != nil {
		return x.OrderBy
	}
	return nil
}

func (x *DocumentQuery) GetSavepointName() string {
	if x != nil {
		return x.SavepointName
	}
	return ""
}

func (x *DocumentQuery) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *DocumentQuery) GetPermissionTarget() string {
	if x != nil {
		return x.PermissionTarget
	}
	return ""
}

func (x *DocumentQuery) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *DocumentQuery) GetWindowFunctions() []*WindowClause {
	if x != nil {
		return x.WindowFunctions
	}
	return nil
}

func (x *DocumentQuery) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *DocumentQuery) GetIsolationLevel() string {
	if x != nil {
		return x.IsolationLevel
	}
	return ""
}

func (x *DocumentQuery) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

func (x *DocumentQuery) GetUpsert() *UpsertClause {
	if x != nil {
		return x.Upsert
	}
	return nil
}

func (x *DocumentQuery) GetBulkData() []*BulkInsertRow {
	if x != nil {
		return x.BulkData
	}
	return nil
}

func (x *DocumentQuery) GetViewName() string {
	if x != nil {
		return x.ViewName
	}
	return ""
}

func (x *DocumentQuery) GetViewQuery() *DocumentQuery {
	if x != nil {
		return x.ViewQuery
	}
	return nil
}

func (x *DocumentQuery) GetDatabaseName() string {
	if x != nil {
		return x.DatabaseName
	}
	return ""
}

func (x *DocumentQuery) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *DocumentQuery) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *DocumentQuery) GetUserRoles() []string {
	if x != nil {
		return x.UserRoles
	}
	return nil
}

func (x *DocumentQuery) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

func (x *DocumentQuery) GetSetOperation() *SetOperationClause {
	if x != nil {
		return x.SetOperation
	}
	return nil
}

func (x *DocumentQuery) GetColumns() []*Expression {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *DocumentQuery) GetSelectColumns() []*SelectColumn {
	if x != nil {
		return x.SelectColumns
	}
	return nil
}

func (x *DocumentQuery) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DocumentQuery) GetHaving() []*QueryCondition {
	if x != nil {
		return x.Having
	}
	return nil
}

func (x *DocumentQuery) GetDistinct() bool {
	if x != nil {
		return x.Distinct
	}
	return false
}

func (x *DocumentQuery) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type KeyValueQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Args          []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	BulkPairs     []*KeyValuePair        `protobuf:"bytes,4,rep,name=bulk_pairs,json=bulkPairs,proto3" json:"bulk_pairs,omitempty"`
	SessionId     string                 `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	CommandString string                 `protobuf:"bytes,6,opt,name=command_string,json=commandString,proto3" json:"command_string,omitempty"`
	// Filtering support
	Entity        string            `protobuf:"bytes,7,opt,name=entity,proto3" json:"entity,omitempty"`                   // Entity name (e.g., "user")
	Conditions    []*QueryCondition `protobuf:"bytes,8,rep,name=conditions,proto3" json:"conditions,omitempty"`           // WHERE conditions
	Limit         int32             `protobuf:"varint,9,opt,name=limit,proto3" json:"limit,omitempty"`                    // LIMIT clause
	Offset        int32             `protobuf:"varint,10,opt,name=offset,proto3" json:"offset,omitempty"`                 // OFFSET clause
	OrderBy       []*OrderByClause  `protobuf:"bytes,11,rep,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"` // ORDER BY clauses
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValueQuery) Reset() {
	*x = KeyValueQuery{}
	mi := &file_utilities_proto_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValueQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValueQuery) ProtoMessage() {}

func (x *KeyValueQuery) ProtoReflect() protoreflect.Message {
	mi := &file_utilities_proto_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValueQuery.ProtoReflect.Descriptor instead.
func (*KeyValueQuery) Descriptor() ([]byte, []int) {
	return file_utilities_proto_events_proto_rawDescGZIP(), []int{8}
}

func (x *KeyValueQuery) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *KeyValueQuery) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValueQuery) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *KeyValueQuery) GetBulkPairs() []*KeyValuePair {
	if x != nil {
		return x.BulkPairs
	}
	return nil
}

func (x *KeyValueQuery) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *KeyValueQuery) GetCommandString() string {
	if x != nil {
		return x.CommandString
	}
	return ""
}

func (x *KeyValueQuery) GetEntity() string {
	if x != nil {
		return x.Entity
	}
	return ""
}

func (x *KeyValueQuery) GetConditions() []*QueryCondition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *KeyValueQuery) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *KeyValueQuery) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *KeyValueQuery) GetOrderBy() []*OrderByClause {
	if x != nil {
		return x.OrderBy
	}
	return nil
}

type KeyValuePair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValuePair) Reset() {
	*x = KeyValuePair{}
	mi := &file_utilities_proto_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValuePair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValuePair) ProtoMessage() {}

func (x *KeyValuePair) ProtoReflect() protoreflect.Message {
	mi := &file_utilities_proto_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValuePair.ProtoReflect.Descriptor instead.
func (*KeyValuePair) Descriptor() ([]byte, []int) {
	return file_utilities_proto_events_proto_rawDescGZIP(), []int{9}
}

func (x *KeyValuePair) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValuePair) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type JoinClause struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JoinType      string                 `protobuf:"bytes,1,opt,name=join_type,json=joinType,proto3" json:"join_type,omitempty"` // INNER, LEFT, RIGHT, FULL, CROSS
	Table         string                 `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	LeftExpr      *Expression            `protobuf:"bytes,3,opt,name=left_expr,json=leftExpr,proto3" json:"left_expr,omitempty"`    // 100% TrueAST
	RightExpr     *Expression            `protobuf:"bytes,4,opt,name=right_expr,json=rightExpr,proto3" json:"right_expr,omitempty"` // 100% TrueAST
	Position      int32                  `protobuf:"varint,5,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinClause) Reset() {
	*x = JoinClause{}
	mi := &file_utilities_proto_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinClause) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinClause) ProtoMessage() {}

func (x *JoinClause) ProtoReflect() protoreflect.Message {
	mi := &file_utilities_proto_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinClause.ProtoReflect.Descriptor instead.
func (*JoinClause) Descriptor() ([]byte, []int) {
	return file_utilities_proto_events_proto_rawDescGZIP(), []int{10}
}

func (x *JoinClause) GetJoinType() string {
	if x != nil {
		return x.JoinType
	}
	return ""
}

func (x *JoinClause) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *JoinClause) GetLeftExpr() *Expression {
	if x != nil {
		return x.LeftExpr
	}
	return nil
}

func (x *JoinClause) GetRightExpr() *Expression {
	if x != nil {
		return x.RightExpr
	}
	return nil
}

func (x *JoinClause) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

type AggregateClause struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Function      string                 `protobuf:"bytes,1,opt,name=function,proto3" json:"function,omitempty"`                    // COUNT, SUM, AVG, MIN, MAX
	FieldExpr     *Expression            `protobuf:"bytes,2,opt,name=field_expr,json=fieldExpr,proto3" json:"field_expr,omitempty"` // 100% TrueAST
	Position      int32                  `protobuf:"varint,3,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregateClause) Reset() {
	*x = AggregateClause{}
	mi := &file_utilities_proto_events_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregateClause) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregateClause) ProtoMessage() {}

func (x *AggregateClause) ProtoReflect() protoreflect.Message {
	mi := &file_utilities_proto_events_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregateClause.ProtoReflect.Descriptor instead.
func (*AggregateClause) Descriptor() ([]byte, []int) {
	return file_utilities_proto_events_proto_rawDescGZIP(), []int{11}
}

func (x *AggregateClause) GetFunction() string {
	if x != nil {
		return x.Function
	}
	return ""
}

func (x *AggregateClause) GetFieldExpr() *Expression {
	if x != nil {
		return x.FieldExpr
	}
	return nil
}

func (x *AggregateClause) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

type OrderByClause struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FieldExpr     *Expression            `protobuf:"bytes,1,opt,name=field_expr,json=fieldExpr,proto3" json:"field_expr,omitempty"` // 100% TrueAST
	Direction     string                 `protobuf:"bytes,2,opt,name=direction,proto3" json:"direction,omitempty"`                  // ASC, DESC
	Position      int32                  `protobuf:"varint,3,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderByClause) Reset() {
	*x = OrderByClause{}
	mi := &file_utilities_proto_events_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderByClause) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderByClause) ProtoMessage() {}

func (x *OrderByClause) ProtoReflect() protoreflect.Message {
	mi := &file_utilities_proto_events_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderByClause.ProtoReflect.Descriptor instead.
func (*OrderByClause) Descriptor() ([]byte, []int) {
	return file_utilities_proto_events_proto_rawDescGZIP(), []int{12}
}

func (x *OrderByClause) GetFieldExpr() *Expression {
	if x != nil {
		return x.FieldExpr
	}
	return nil
}

func (x *OrderByClause) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *OrderByClause) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

type WindowClause struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Function      string                 `protobuf:"bytes,1,opt,name=function,proto3" json:"function,omitempty"`                    // ROW NUMBER, RANK, etc.
	FieldExpr     *Expression            `protobuf:"bytes,2,opt,name=field_expr,json=fieldExpr,proto3" json:"field_expr,omitempty"` // 100% TrueAST
	Alias         string                 `protobuf:"bytes,3,opt,name=alias,proto3" json:"alias,omitempty"`
	PartitionBy   []*Expression          `protobuf:"bytes,4,rep,name=partition_by,json=partitionBy,proto3" json:"partition_by,omitempty"` // 100% TrueAST
	OrderBy       []*OrderByClause       `protobuf:"bytes,5,rep,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	Offset        int32                  `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`
	Buckets       int32                  `protobuf:"varint,7,opt,name=buckets,proto3" json:"buckets,omitempty"`
	Position      int32                  `protobuf:"varint,8,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WindowClause) Reset() {
	*x = WindowClause{}
	mi := &file_utilities_proto_events_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WindowClause) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WindowClause) ProtoMessage() {}

func (x *WindowClause) ProtoReflect() protoreflect.Message {
	mi := &file_utilities_proto_events_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WindowClause.ProtoReflect.Descriptor instead.
func (*WindowClause) Descriptor() ([]byte, []int) {
	return file_utilities_proto_events_proto_rawDescGZIP(), []int{13}
}

func (x *WindowClause) GetFunction() string {
	if x != nil {
		return x.Function
	}
	return ""
}

func (x *WindowClause) GetFieldExpr() *Expression {
	if x != nil {
		return x.FieldExpr
	}
	return nil
}

func (x *WindowClause) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *WindowClause) GetPartitionBy() []*Expression {
	if x != nil {
		return x.PartitionBy
	}
	return nil
}

func (x *WindowClause) GetOrderBy() []*OrderByClause {
	if x != nil {
		return x.OrderBy
	}
	return nil
}

func (x *WindowClause) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *WindowClause) GetBuckets() int32 {
	if x != nil {
		return x.Buckets
	}
	return 0
}

func (x *WindowClause) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

type CTEClause struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CteName        string                 `protobuf:"bytes,1,opt,name=cte_name,json=cteName,proto3" json:"cte_name,omitempty"`
	CteQuery       *RelationalQuery       `protobuf:"bytes,2,opt,name=cte_query,json=cteQuery,proto3" json:"cte_query,omitempty"` // 100% TrueAST
	Recursive      bool                   `protobuf:"varint,3,opt,name=recursive,proto3" json:"recursive,omitempty"`
	AdditionalCtes []*CTEClause           `protobuf:"bytes,4,rep,name=additional_ctes,json=additionalCtes,proto3" json:"additional_ctes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CTEClause) Reset() {
	*x = CTEClause{}
	mi := &file_utilities_proto_events_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CTEClause) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CTEClause) ProtoMessage() {}

func (x *CTEClause) ProtoReflect() protoreflect.Message {
	mi := &file_utilities_proto_events_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CTEClause.ProtoReflect.Descriptor instead.
func (*CTEClause) Descriptor() ([]byte, []int) {
	return file_utilities_proto_events_proto_rawDescGZIP(), []int{14}
}

func (x *CTEClause) GetCteName() string {
	if x != nil {
		return x.CteName
	}
	return ""
}

func (x *CTEClause) GetCteQuery() *RelationalQuery {
	if x != nil {
		return x.CteQuery
	}
	return nil
}

func (x *CTEClause) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

func (x *CTEClause) GetAdditionalCtes() []*CTEClause {
	if x != nil {
		return x.AdditionalCtes
	}
	return nil
}

type SubqueryClause struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubqueryType  string                 `protobuf:"bytes,1,opt,name=subquery_type,json=subqueryType,proto3" json:"subquery_type,omitempty"` // IN, EXISTS, NOT_IN, NOT_EXISTS, SCALAR
	FieldExpr     *Expression            `protobuf:"bytes,2,opt,name=field_expr,json=fieldExpr,proto3" json:"field_expr,omitempty"`          // 100% TrueAST
	Subquery      *RelationalQuery       `protobuf:"bytes,3,opt,name=subquery,proto3" json:"subquery,omitempty"`                             // 100% TrueAST
	Alias         string                 `protobuf:"bytes,4,opt,name=alias,proto3" json:"alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubqueryClause) Reset() {
	*x = SubqueryClause{}
	mi := &file_utilities_proto_events_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubqueryClause) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubqueryClause) ProtoMessage() {}

func (x *SubqueryClause) ProtoReflect() protoreflect.Message {
	mi := &file_utilities_proto_events_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubqueryClause.ProtoReflect.Descriptor instead.
func (*SubqueryClause) Descriptor() ([]byte, []int) {
	return file_utilities_proto_events_proto_rawDescGZIP(), []int{15}
}

func (x *SubqueryClause) GetSubqueryType() string {
	if x != nil {
		return x.SubqueryType
	}
	return ""
}

func (x *SubqueryClause) GetFieldExpr() *Expression {
	if x != nil {
		return x.FieldExpr
	}
	return nil
}

func (x *SubqueryClause) GetSubquery() *RelationalQuery {
	if x != nil {
		return x.Subquery
	}
	return nil
}

func (x *SubqueryClause) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

type UpsertClause struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConflictFields []*Expression          `protobuf:"bytes,1,rep,name=conflict_fields,json=conflictFields,proto3" json:"conflict_fields,omitempty"` // 100% TrueAST
	UpdateFields   []*QueryField          `protobuf:"bytes,2,rep,name=update_fields,json=updateFields,proto3" json:"update_fields,omitempty"`
	ConflictAction string                 `protobuf:"bytes,3,opt,name=conflict_action,json=conflictAction,proto3" json:"conflict_action,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpsertClause) Reset() {
	*x = UpsertClause{}
	mi := &file_utilities_proto_events_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertClause) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertClause) ProtoMessage() {}

func (x *UpsertClause) ProtoReflect() protoreflect.Message {
	mi := &file_utilities_proto_events_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertClause.ProtoReflect.Descriptor instead.
func (*UpsertClause) Descriptor() ([]byte, []int) {
	return file_utilities_proto_events_proto_rawDescGZIP(), []int{16}
}

func (x *UpsertClause) GetConflictFields() []*Expression {
	if x != nil {
		return x.ConflictFields
	}
	return nil
}

func (x *UpsertClause) GetUpdateFields() []*QueryField {
	if x != nil {
		return x.UpdateFields
	}
	return nil
}

func (x *UpsertClause) GetConflictAction() string {
	if x != nil {
		return x.ConflictAction
	}
	return ""
}

type BulkInsertRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        []*QueryField          `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkInsertRow) Reset() {
	*x = BulkInsertRow{}
	mi := &file_utilities_proto_events_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkInsertRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkInsertRow) ProtoMessage() {}

func (x *BulkInsertRow) ProtoReflect() protoreflect.Message {
	mi := &file_utilities_proto_events_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkInsertRow.ProtoReflect.Descriptor instead.
func (*BulkInsertRow) Descriptor() ([]byte, []int) {
	return file_utilities_proto_events_proto_rawDescGZIP(), []int{17}
}

func (x *BulkInsertRow) GetFields() []*QueryField {
	if x != nil {
		return x.Fields
	}
	return nil
}

type SetOperationClause struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationType string                 `protobuf:"bytes,1,opt,name=operation_type,json=operationType,proto3" json:"operation_type,omitempty"` // UNION, UNION ALL, INTERSECT, EXCEPT
	LeftQuery     *RelationalQuery       `protobuf:"bytes,2,opt,name=left_query,json=leftQuery,proto3" json:"left_query,omitempty"`
	RightQuery    *RelationalQuery       `protobuf:"bytes,3,opt,name=right_query,json=rightQuery,proto3" json:"right_query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetOperationClause) Reset() {
	*x = SetOperationClause{}
	mi := &file_utilities_proto_events_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetOperationClause) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetOperationClause) ProtoMessage() {}

func (x *SetOperationClause) ProtoReflect() protoreflect.Message {
	mi := &file_utilities_proto_events_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetOperationClause.ProtoReflect.Descriptor instead.
func (*SetOperationClause) Descriptor() ([]byte, []int) {
	return file_utilities_proto_events_proto_rawDescGZIP(), []int{18}
}

func (x *SetOperationClause) GetOperationType() string {
	if x != nil {
		return x.OperationType
	}
	return ""
}

func (x *SetOperationClause) GetLeftQuery() *RelationalQuery {
	if x != nil {
		return x.LeftQuery
	}
	return nil
}

func (x *SetOperationClause) GetRightQuery() *RelationalQuery {
	if x != nil {
		return x.RightQuery
	}
	return nil
}

var File_utilities_proto_events_proto protoreflect.FileDescriptor

const file_utilities_proto_events_proto_rawDesc = "" +
	"\n" +
	"\x1cutilities/proto/events.proto\x12\x06omniql\"\xc4\x01\n" +
	"\x0eUniversalQuery\x129\n" +
	"\n" +
	"relational\x18\x01 \x01(\v2\x17.omniql.RelationalQueryH\x00R\n" +
	"relational\x123\n" +
	"\bdocument\x18\x02 \x01(\v2\x15.omniql.DocumentQueryH\x00R\bdocument\x124\n" +
	"\tkey_value\x18\x03 \x01(\v2\x15.omniql.KeyValueQueryH\x00R\bkeyValueB\f\n" +
	"\n" +
	"query_type\"\x8f\x03\n" +
	"\n" +
	"Expression\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1a\n" +
	"\bposition\x18\x02 \x01(\x05R\bposition\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12&\n" +
	"\x04left\x18\x04 \x01(\v2\x12.omniql.ExpressionR\x04left\x12\x1a\n" +
	"\boperator\x18\x05 \x01(\tR\boperator\x12(\n" +
	"\x05right\x18\x06 \x01(\v2\x12.omniql.ExpressionR\x05right\x12#\n" +
	"\rfunction_name\x18\a \x01(\tR\ffunctionName\x127\n" +
	"\rfunction_args\x18\b \x03(\v2\x12.omniql.ExpressionR\ffunctionArgs\x12>\n" +
	"\x0fcase_conditions\x18\t \x03(\v2\x15.omniql.CaseConditionR\x0ecaseConditions\x12/\n" +
	"\tcase_else\x18\n" +
	" \x01(\v2\x12.omniql.ExpressionR\bcaseElse\"\xde\x02\n" +
	"\x0eQueryCondition\x121\n" +
	"\n" +
	"field_expr\x18\x01 \x01(\v2\x12.omniql.ExpressionR\tfieldExpr\x12\x1a\n" +
	"\boperator\x18\x02 \x01(\tR\boperator\x121\n" +
	"\n" +
	"value_expr\x18\x03 \x01(\v2\x12.omniql.ExpressionR\tvalueExpr\x123\n" +
	"\vvalue2_expr\x18\x04 \x01(\v2\x12.omniql.ExpressionR\n" +
	"value2Expr\x123\n" +
	"\vvalues_expr\x18\x05 \x03(\v2\x12.omniql.ExpressionR\n" +
	"valuesExpr\x12\x14\n" +
	"\x05logic\x18\x06 \x01(\tR\x05logic\x12.\n" +
	"\x06nested\x18\a \x03(\v2\x16.omniql.QueryConditionR\x06nested\x12\x1a\n" +
	"\bposition\x18\b \x01(\x05R\bposition\"\x92\x01\n" +
	"\rCaseCondition\x124\n" +
	"\tcondition\x18\x01 \x01(\v2\x16.omniql.QueryConditionR\tcondition\x12/\n" +
	"\tthen_expr\x18\x02 \x01(\v2\x12.omniql.ExpressionR\bthenExpr\x12\x1a\n" +
	"\bposition\x18\x03 \x01(\x05R\bposition\"\xae\x01\n" +
	"\n" +
	"QueryField\x12/\n" +
	"\tname_expr\x18\x01 \x01(\v2\x12.omniql.ExpressionR\bnameExpr\x121\n" +
	"\n" +
	"value_expr\x18\x02 \x01(\v2\x12.omniql.ExpressionR\tvalueExpr\x12 \n" +
	"\vconstraints\x18\x03 \x03(\tR\vconstraints\x12\x1a\n" +
	"\bposition\x18\x04 \x01(\x05R\bposition\"{\n" +
	"\fSelectColumn\x129\n" +
	"\x0eexpression_obj\x18\x01 \x01(\v2\x12.omniql.ExpressionR\rexpressionObj\x12\x14\n" +
	"\x05alias\x18\x02 \x01(\tR\x05alias\x12\x1a\n" +
	"\bposition\x18\x03 \x01(\x05R\bposition\"\x80\x17\n" +
	"\x0fRelationalQuery\x12\x1c\n" +
	"\toperation\x18\x01 \x01(\tR\toperation\x12\x14\n" +
	"\x05table\x18\x02 \x01(\tR\x05table\x126\n" +
	"\n" +
	"conditions\x18\x03 \x03(\v2\x16.omniql.QueryConditionR\n" +
	"conditions\x12*\n" +
	"\x06fields\x18\x04 \x03(\v2\x12.omniql.QueryFieldR\x06fields\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x06 \x01(\x05R\x06offset\x12\x1a\n" +
	"\bdistinct\x18\a \x01(\bR\bdistinct\x12%\n" +
	"\x0etransaction_id\x18\b \x01(\tR\rtransactionId\x12(\n" +
	"\x05joins\x18\t \x03(\v2\x12.omniql.JoinClauseR\x05joins\x125\n" +
	"\taggregate\x18\n" +
	" \x01(\v2\x17.omniql.AggregateClauseR\taggregate\x12-\n" +
	"\bgroup_by\x18\v \x03(\v2\x12.omniql.ExpressionR\agroupBy\x12.\n" +
	"\x06having\x18\f \x03(\v2\x16.omniql.QueryConditionR\x06having\x120\n" +
	"\border_by\x18\r \x03(\v2\x15.omniql.OrderByClauseR\aorderBy\x12%\n" +
	"\x0esavepoint_name\x18\x0e \x01(\tR\rsavepointName\x12 \n" +
	"\vpermissions\x18\x0f \x03(\tR\vpermissions\x12+\n" +
	"\x11permission_target\x18\x10 \x01(\tR\x10permissionTarget\x12\x1b\n" +
	"\trole_name\x18\x11 \x01(\tR\broleName\x12?\n" +
	"\x10window_functions\x18\x12 \x03(\v2\x14.omniql.WindowClauseR\x0fwindowFunctions\x12#\n" +
	"\x03cte\x18\x13 \x01(\v2\x11.omniql.CTEClauseR\x03cte\x122\n" +
	"\bsubquery\x18\x14 \x01(\v2\x16.omniql.SubqueryClauseR\bsubquery\x12\x18\n" +
	"\apattern\x18\x15 \x01(\tR\apattern\x12'\n" +
	"\x0fisolation_level\x18\x16 \x01(\tR\x0eisolationLevel\x12\x1b\n" +
	"\tread_only\x18\x17 \x01(\bR\breadOnly\x12,\n" +
	"\x06upsert\x18\x18 \x01(\v2\x14.omniql.UpsertClauseR\x06upsert\x122\n" +
	"\tbulk_data\x18\x19 \x03(\v2\x15.omniql.BulkInsertRowR\bbulkData\x12\x1b\n" +
	"\tview_name\x18\x1a \x01(\tR\bviewName\x126\n" +
	"\n" +
	"view_query\x18\x1b \x01(\v2\x17.omniql.RelationalQueryR\tviewQuery\x12#\n" +
	"\rdatabase_name\x18\x1c \x01(\tR\fdatabaseName\x12\x19\n" +
	"\bnew_name\x18\x1d \x01(\tR\anewName\x12\x1b\n" +
	"\tuser_name\x18\x1e \x01(\tR\buserName\x12\x1a\n" +
	"\bpassword\x18\x1f \x01(\tR\bpassword\x12\x1d\n" +
	"\n" +
	"user_roles\x18  \x03(\tR\tuserRoles\x12?\n" +
	"\rset_operation\x18! \x01(\v2\x1a.omniql.SetOperationClauseR\fsetOperation\x12,\n" +
	"\acolumns\x18\" \x03(\v2\x12.omniql.ExpressionR\acolumns\x12;\n" +
	"\x0eselect_columns\x18# \x03(\v2\x14.omniql.SelectColumnR\rselectColumns\x12\x1d\n" +
	"\n" +
	"session_id\x18$ \x01(\tR\tsessionId\x12\x10\n" +
	"\x03sql\x18% \x01(\tR\x03sql\x12!\n" +
	"\falter_action\x18& \x01(\tR\valterAction\x12#\n" +
	"\rsequence_name\x18' \x01(\tR\fsequenceName\x12%\n" +
	"\x0esequence_start\x18( \x01(\x03R\rsequenceStart\x12-\n" +
	"\x12sequence_increment\x18) \x01(\x03R\x11sequenceIncrement\x12!\n" +
	"\fsequence_min\x18* \x01(\x03R\vsequenceMin\x12!\n" +
	"\fsequence_max\x18+ \x01(\x03R\vsequenceMax\x12%\n" +
	"\x0esequence_cache\x18, \x01(\x03R\rsequenceCache\x12%\n" +
	"\x0esequence_cycle\x18- \x01(\bR\rsequenceCycle\x12)\n" +
	"\x10sequence_restart\x18. \x01(\x03R\x0fsequenceRestart\x12%\n" +
	"\x0eextension_name\x18/ \x01(\tR\rextensionName\x12\x1f\n" +
	"\vschema_name\x180 \x01(\tR\n" +
	"schemaName\x12!\n" +
	"\fschema_owner\x181 \x01(\tR\vschemaOwner\x12\x1b\n" +
	"\ttype_name\x182 \x01(\tR\btypeName\x12\x1b\n" +
	"\ttype_kind\x183 \x01(\tR\btypeKind\x12\x1f\n" +
	"\venum_values\x184 \x03(\tR\n" +
	"enumValues\x12\x1d\n" +
	"\n" +
	"enum_value\x185 \x01(\tR\tenumValue\x12$\n" +
	"\x0enew_enum_value\x186 \x01(\tR\fnewEnumValue\x12\x1f\n" +
	"\vdomain_name\x187 \x01(\tR\n" +
	"domainName\x12\x1f\n" +
	"\vdomain_type\x188 \x01(\tR\n" +
	"domainType\x12%\n" +
	"\x0edomain_default\x189 \x01(\tR\rdomainDefault\x12+\n" +
	"\x11domain_constraint\x18: \x01(\tR\x10domainConstraint\x12\x1b\n" +
	"\tfunc_name\x18; \x01(\tR\bfuncName\x12\x1b\n" +
	"\tfunc_body\x18< \x01(\tR\bfuncBody\x12\x1b\n" +
	"\tfunc_args\x18= \x03(\tR\bfuncArgs\x12!\n" +
	"\ffunc_returns\x18> \x01(\tR\vfuncReturns\x12#\n" +
	"\rfunc_language\x18? \x01(\tR\ffuncLanguage\x12\x1d\n" +
	"\n" +
	"func_owner\x18@ \x01(\tR\tfuncOwner\x12!\n" +
	"\ftrigger_name\x18A \x01(\tR\vtriggerName\x12%\n" +
	"\x0etrigger_timing\x18B \x01(\tR\rtriggerTiming\x12%\n" +
	"\x0etrigger_events\x18C \x01(\tR\rtriggerEvents\x12(\n" +
	"\x10trigger_for_each\x18D \x01(\tR\x0etriggerForEach\x12\x1f\n" +
	"\vpolicy_name\x18E \x01(\tR\n" +
	"policyName\x12\x1d\n" +
	"\n" +
	"policy_for\x18F \x01(\tR\tpolicyFor\x12\x1b\n" +
	"\tpolicy_to\x18G \x01(\tR\bpolicyTo\x12!\n" +
	"\fpolicy_using\x18H \x01(\tR\vpolicyUsing\x12!\n" +
	"\fpolicy_check\x18I \x01(\tR\vpolicyCheck\x12\x1b\n" +
	"\trule_name\x18J \x01(\tR\bruleName\x12\x1d\n" +
	"\n" +
	"rule_event\x18K \x01(\tR\truleEvent\x12\x1f\n" +
	"\vrule_action\x18L \x01(\tR\n" +
	"ruleAction\x12%\n" +
	"\x0ecomment_target\x18M \x01(\tR\rcommentTarget\x12!\n" +
	"\fcomment_text\x18N \x01(\tR\vcommentText\x12\x18\n" +
	"\acascade\x18O \x01(\bR\acascade\"\xcb\n" +
	"\n" +
	"\rDocumentQuery\x12\x1c\n" +
	"\toperation\x18\x01 \x01(\tR\toperation\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\x126\n" +
	"\n" +
	"conditions\x18\x03 \x03(\v2\x16.omniql.QueryConditionR\n" +
	"conditions\x12*\n" +
	"\x06fields\x18\x04 \x03(\v2\x12.omniql.QueryFieldR\x06fields\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\x12\x12\n" +
	"\x04skip\x18\x06 \x01(\x05R\x04skip\x12(\n" +
	"\x05joins\x18\a \x03(\v2\x12.omniql.JoinClauseR\x05joins\x125\n" +
	"\taggregate\x18\b \x01(\v2\x17.omniql.AggregateClauseR\taggregate\x12-\n" +
	"\bgroup_by\x18\t \x03(\v2\x12.omniql.ExpressionR\agroupBy\x120\n" +
	"\border_by\x18\n" +
	" \x03(\v2\x15.omniql.OrderByClauseR\aorderBy\x12%\n" +
	"\x0esavepoint_name\x18\v \x01(\tR\rsavepointName\x12 \n" +
	"\vpermissions\x18\f \x03(\tR\vpermissions\x12+\n" +
	"\x11permission_target\x18\r \x01(\tR\x10permissionTarget\x12\x1b\n" +
	"\trole_name\x18\x0e \x01(\tR\broleName\x12?\n" +
	"\x10window_functions\x18\x0f \x03(\v2\x14.omniql.WindowClauseR\x0fwindowFunctions\x12\x18\n" +
	"\apattern\x18\x10 \x01(\tR\apattern\x12'\n" +
	"\x0fisolation_level\x18\x11 \x01(\tR\x0eisolationLevel\x12\x1b\n" +
	"\tread_only\x18\x12 \x01(\bR\breadOnly\x12,\n" +
	"\x06upsert\x18\x13 \x01(\v2\x14.omniql.UpsertClauseR\x06upsert\x122\n" +
	"\tbulk_data\x18\x14 \x03(\v2\x15.omniql.BulkInsertRowR\bbulkData\x12\x1b\n" +
	"\tview_name\x18\x15 \x01(\tR\bviewName\x124\n" +
	"\n" +
	"view_query\x18\x16 \x01(\v2\x15.omniql.DocumentQueryR\tviewQuery\x12#\n" +
	"\rdatabase_name\x18\x17 \x01(\tR\fdatabaseName\x12\x1b\n" +
	"\tuser_name\x18\x18 \x01(\tR\buserName\x12\x1a\n" +
	"\bpassword\x18\x19 \x01(\tR\bpassword\x12\x1d\n" +
	"\n" +
	"user_roles\x18\x1a \x03(\tR\tuserRoles\x12\x19\n" +
	"\bnew_name\x18\x1b \x01(\tR\anewName\x12?\n" +
	"\rset_operation\x18\x1c \x01(\v2\x1a.omniql.SetOperationClauseR\fsetOperation\x12,\n" +
	"\acolumns\x18\x1d \x03(\v2\x12.omniql.ExpressionR\acolumns\x12;\n" +
	"\x0eselect_columns\x18\x1e \x03(\v2\x14.omniql.SelectColumnR\rselectColumns\x12\x1d\n" +
	"\n" +
	"session_id\x18\x1f \x01(\tR\tsessionId\x12.\n" +
	"\x06having\x18  \x03(\v2\x16.omniql.QueryConditionR\x06having\x12\x1a\n" +
	"\bdistinct\x18! \x01(\bR\bdistinct\x12\x14\n" +
	"\x05query\x18\" \x01(\tR\x05query\"\xfa\x02\n" +
	"\rKeyValueQuery\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x123\n" +
	"\n" +
	"bulk_pairs\x18\x04 \x03(\v2\x14.omniql.KeyValuePairR\tbulkPairs\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\x12%\n" +
	"\x0ecommand_string\x18\x06 \x01(\tR\rcommandString\x12\x16\n" +
	"\x06entity\x18\a \x01(\tR\x06entity\x126\n" +
	"\n" +
	"conditions\x18\b \x03(\v2\x16.omniql.QueryConditionR\n" +
	"conditions\x12\x14\n" +
	"\x05limit\x18\t \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\n" +
	" \x01(\x05R\x06offset\x120\n" +
	"\border_by\x18\v \x03(\v2\x15.omniql.OrderByClauseR\aorderBy\"6\n" +
	"\fKeyValuePair\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xbf\x01\n" +
	"\n" +
	"JoinClause\x12\x1b\n" +
	"\tjoin_type\x18\x01 \x01(\tR\bjoinType\x12\x14\n" +
	"\x05table\x18\x02 \x01(\tR\x05table\x12/\n" +
	"\tleft_expr\x18\x03 \x01(\v2\x12.omniql.ExpressionR\bleftExpr\x121\n" +
	"\n" +
	"right_expr\x18\x04 \x01(\v2\x12.omniql.ExpressionR\trightExpr\x12\x1a\n" +
	"\bposition\x18\x05 \x01(\x05R\bposition\"|\n" +
	"\x0fAggregateClause\x12\x1a\n" +
	"\bfunction\x18\x01 \x01(\tR\bfunction\x121\n" +
	"\n" +
	"field_expr\x18\x02 \x01(\v2\x12.omniql.ExpressionR\tfieldExpr\x12\x1a\n" +
	"\bposition\x18\x03 \x01(\x05R\bposition\"|\n" +
	"\rOrderByClause\x121\n" +
	"\n" +
	"field_expr\x18\x01 \x01(\v2\x12.omniql.ExpressionR\tfieldExpr\x12\x1c\n" +
	"\tdirection\x18\x02 \x01(\tR\tdirection\x12\x1a\n" +
	"\bposition\x18\x03 \x01(\x05R\bposition\"\xaa\x02\n" +
	"\fWindowClause\x12\x1a\n" +
	"\bfunction\x18\x01 \x01(\tR\bfunction\x121\n" +
	"\n" +
	"field_expr\x18\x02 \x01(\v2\x12.omniql.ExpressionR\tfieldExpr\x12\x14\n" +
	"\x05alias\x18\x03 \x01(\tR\x05alias\x125\n" +
	"\fpartition_by\x18\x04 \x03(\v2\x12.omniql.ExpressionR\vpartitionBy\x120\n" +
	"\border_by\x18\x05 \x03(\v2\x15.omniql.OrderByClauseR\aorderBy\x12\x16\n" +
	"\x06offset\x18\x06 \x01(\x05R\x06offset\x12\x18\n" +
	"\abuckets\x18\a \x01(\x05R\abuckets\x12\x1a\n" +
	"\bposition\x18\b \x01(\x05R\bposition\"\xb6\x01\n" +
	"\tCTEClause\x12\x19\n" +
	"\bcte_name\x18\x01 \x01(\tR\acteName\x124\n" +
	"\tcte_query\x18\x02 \x01(\v2\x17.omniql.RelationalQueryR\bcteQuery\x12\x1c\n" +
	"\trecursive\x18\x03 \x01(\bR\trecursive\x12:\n" +
	"\x0fadditional_ctes\x18\x04 \x03(\v2\x11.omniql.CTEClauseR\x0eadditionalCtes\"\xb3\x01\n" +
	"\x0eSubqueryClause\x12#\n" +
	"\rsubquery_type\x18\x01 \x01(\tR\fsubqueryType\x121\n" +
	"\n" +
	"field_expr\x18\x02 \x01(\v2\x12.omniql.ExpressionR\tfieldExpr\x123\n" +
	"\bsubquery\x18\x03 \x01(\v2\x17.omniql.RelationalQueryR\bsubquery\x12\x14\n" +
	"\x05alias\x18\x04 \x01(\tR\x05alias\"\xad\x01\n" +
	"\fUpsertClause\x12;\n" +
	"\x0fconflict_fields\x18\x01 \x03(\v2\x12.omniql.ExpressionR\x0econflictFields\x127\n" +
	"\rupdate_fields\x18\x02 \x03(\v2\x12.omniql.QueryFieldR\fupdateFields\x12'\n" +
	"\x0fconflict_action\x18\x03 \x01(\tR\x0econflictAction\";\n" +
	"\rBulkInsertRow\x12*\n" +
	"\x06fields\x18\x01 \x03(\v2\x12.omniql.QueryFieldR\x06fields\"\xad\x01\n" +
	"\x12SetOperationClause\x12%\n" +
	"\x0eoperation_type\x18\x01 \x01(\tR\roperationType\x126\n" +
	"\n" +
	"left_query\x18\x02 \x01(\v2\x17.omniql.RelationalQueryR\tleftQuery\x128\n" +
	"\vright_query\x18\x03 \x01(\v2\x17.omniql.RelationalQueryR\n" +
	"rightQueryB1Z/github.com/omniql-engine/omniql/utilities/protob\x06proto3"

var (
	file_utilities_proto_events_proto_rawDescOnce sync.Once
	file_utilities_proto_events_proto_rawDescData []byte
)

func file_utilities_proto_events_proto_rawDescGZIP() []byte {
	file_utilities_proto_events_proto_rawDescOnce.Do(func() {
		file_utilities_proto_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_utilities_proto_events_proto_rawDesc), len(file_utilities_proto_events_proto_rawDesc)))
	})
	return file_utilities_proto_events_proto_rawDescData
}

var file_utilities_proto_events_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_utilities_proto_events_proto_goTypes = []any{
	(*UniversalQuery)(nil),     // 0: omniql.UniversalQuery
	(*Expression)(nil),         // 1: omniql.Expression
	(*QueryCondition)(nil),     // 2: omniql.QueryCondition
	(*CaseCondition)(nil),      // 3: omniql.CaseCondition
	(*QueryField)(nil),         // 4: omniql.QueryField
	(*SelectColumn)(nil),       // 5: omniql.SelectColumn
	(*RelationalQuery)(nil),    // 6: omniql.RelationalQuery
	(*DocumentQuery)(nil),      // 7: omniql.DocumentQuery
	(*KeyValueQuery)(nil),      // 8: omniql.KeyValueQuery
	(*KeyValuePair)(nil),       // 9: omniql.KeyValuePair
	(*JoinClause)(nil),         // 10: omniql.JoinClause
	(*AggregateClause)(nil),    // 11: omniql.AggregateClause
	(*OrderByClause)(nil),      // 12: omniql.OrderByClause
	(*WindowClause)(nil),       // 13: omniql.WindowClause
	(*CTEClause)(nil),          // 14: omniql.CTEClause
	(*SubqueryClause)(nil),     // 15: omniql.SubqueryClause
	(*UpsertClause)(nil),       // 16: omniql.UpsertClause
	(*BulkInsertRow)(nil),      // 17: omniql.BulkInsertRow
	(*SetOperationClause)(nil), // 18: omniql.SetOperationClause
}
var file_utilities_proto_events_proto_depIdxs = []int32{
	6,  // 0: omniql.UniversalQuery.relational:type_name -> omniql.RelationalQuery
	7,  // 1: omniql.UniversalQuery.document:type_name -> omniql.DocumentQuery
	8,  // 2: omniql.UniversalQuery.key_value:type_name -> omniql.KeyValueQuery
	1,  // 3: omniql.Expression.left:type_name -> omniql.Expression
	1,  // 4: omniql.Expression.right:type_name -> omniql.Expression
	1,  // 5: omniql.Expression.function_args:type_name -> omniql.Expression
	3,  // 6: omniql.Expression.case_conditions:type_name -> omniql.CaseCondition
	1,  // 7: omniql.Expression.case_else:type_name -> omniql.Expression
	1,  // 8: omniql.QueryCondition.field_expr:type_name -> omniql.Expression
	1,  // 9: omniql.QueryCondition.value_expr:type_name -> omniql.Expression
	1,  // 10: omniql.QueryCondition.value2_expr:type_name -> omniql.Expression
	1,  // 11: omniql.QueryCondition.values_expr:type_name -> omniql.Expression
	2,  // 12: omniql.QueryCondition.nested:type_name -> omniql.QueryCondition
	2,  // 13: omniql.CaseCondition.condition:type_name -> omniql.QueryCondition
	1,  // 14: omniql.CaseCondition.then_expr:type_name -> omniql.Expression
	1,  // 15: omniql.QueryField.name_expr:type_name -> omniql.Expression
	1,  // 16: omniql.QueryField.value_expr:type_name -> omniql.Expression
	1,  // 17: omniql.SelectColumn.expression_obj:type_name -> omniql.Expression
	2,  // 18: omniql.RelationalQuery.conditions:type_name -> omniql.QueryCondition
	4,  // 19: omniql.RelationalQuery.fields:type_name -> omniql.QueryField
	10, // 20: omniql.RelationalQuery.joins:type_name -> omniql.JoinClause
	11, // 21: omniql.RelationalQuery.aggregate:type_name -> omniql.AggregateClause
	1,  // 22: omniql.RelationalQuery.group_by:type_name -> omniql.Expression
	2,  // 23: omniql.RelationalQuery.having:type_name -> omniql.QueryCondition
	12, // 24: omniql.RelationalQuery.order_by:type_name -> omniql.OrderByClause
	13, // 25: omniql.RelationalQuery.window_functions:type_name -> omniql.WindowClause
	14, // 26: omniql.RelationalQuery.cte:type_name -> omniql.CTEClause
	15, // 27: omniql.RelationalQuery.subquery:type_name -> omniql.SubqueryClause
	16, // 28: omniql.RelationalQuery.upsert:type_name -> omniql.UpsertClause
	17, // 29: omniql.RelationalQuery.bulk_data:type_name -> omniql.BulkInsertRow
	6,  // 30: omniql.RelationalQuery.view_query:type_name -> omniql.RelationalQuery
	18, // 31: omniql.RelationalQuery.set_operation:type_name -> omniql.SetOperationClause
	1,  // 32: omniql.RelationalQuery.columns:type_name -> omniql.Expression
	5,  // 33: omniql.RelationalQuery.select_columns:type_name -> omniql.SelectColumn
	2,  // 34: omniql.DocumentQuery.conditions:type_name -> omniql.QueryCondition
	4,  // 35: omniql.DocumentQuery.fields:type_name -> omniql.QueryField
	10, // 36: omniql.DocumentQuery.joins:type_name -> omniql.JoinClause
	11, // 37: omniql.DocumentQuery.aggregate:type_name -> omniql.AggregateClause
	1,  // 38: omniql.DocumentQuery.group_by:type_name -> omniql.Expression
	12, // 39: omniql.DocumentQuery.order_by:type_name -> omniql.OrderByClause
	13, // 40: omniql.DocumentQuery.window_functions:type_name -> omniql.WindowClause
	16, // 41: omniql.DocumentQuery.upsert:type_name -> omniql.UpsertClause
	17, // 42: omniql.DocumentQuery.bulk_data:type_name -> omniql.BulkInsertRow
	7,  // 43: omniql.DocumentQuery.view_query:type_name -> omniql.DocumentQuery
	18, // 44: omniql.DocumentQuery.set_operation:type_name -> omniql.SetOperationClause
	1,  // 45: omniql.DocumentQuery.columns:type_name -> omniql.Expression
	5,  // 46: omniql.DocumentQuery.select_columns:type_name -> omniql.SelectColumn
	2,  // 47: omniql.DocumentQuery.having:type_name -> omniql.QueryCondition
	9,  // 48: omniql.KeyValueQuery.bulk_pairs:type_name -> omniql.KeyValuePair
	2,  // 49: omniql.KeyValueQuery.conditions:type_name -> omniql.QueryCondition
	12, // 50: omniql.KeyValueQuery.order_by:type_name -> omniql.OrderByClause
	1,  // 51: omniql.JoinClause.left_expr:type_name -> omniql.Expression
	1,  // 52: omniql.JoinClause.right_expr:type_name -> omniql.Expression
	1,  // 53: omniql.AggregateClause.field_expr:type_name -> omniql.Expression
	1,  // 54: omniql.OrderByClause.field_expr:type_name -> omniql.Expression
	1,  // 55: omniql.WindowClause.field_expr:type_name -> omniql.Expression
	1,  // 56: omniql.WindowClause.partition_by:type_name -> omniql.Expression
	12, // 57: omniql.WindowClause.order_by:type_name -> omniql.OrderByClause
	6,  // 58: omniql.CTEClause.cte_query:type_name -> omniql.RelationalQuery
	14, // 59: omniql.CTEClause.additional_ctes:type_name -> omniql.CTEClause
	1,  // 60: omniql.SubqueryClause.field_expr:type_name -> omniql.Expression
	6,  // 61: omniql.SubqueryClause.subquery:type_name -> omniql.RelationalQuery
	1,  // 62: omniql.UpsertClause.conflict_fields:type_name -> omniql.Expression
	4,  // 63: omniql.UpsertClause.update_fields:type_name -> omniql.QueryField
	4,  // 64: omniql.BulkInsertRow.fields:type_name -> omniql.QueryField
	6,  // 65: omniql.SetOperationClause.left_query:type_name -> omniql.RelationalQuery
	6,  // 66: omniql.SetOperationClause.right_query:type_name -> omniql.RelationalQuery
	67, // [67:67] is the sub-list for method output_type
	67, // [67:67] is the sub-list for method input_type
	67, // [67:67] is the sub-list for extension type_name
	67, // [67:67] is the sub-list for extension extendee
	0,  // [0:67] is the sub-list for field type_name
}

func init() { file_utilities_proto_events_proto_init() }
func file_utilities_proto_events_proto_init() {
	if File_utilities_proto_events_proto != nil {
		return
	}
	file_utilities_proto_events_proto_msgTypes[0].OneofWrappers = []any{
		(*UniversalQuery_Relational)(nil),
		(*UniversalQuery_Document)(nil),
		(*UniversalQuery_KeyValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_utilities_proto_events_proto_rawDesc), len(file_utilities_proto_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_utilities_proto_events_proto_goTypes,
		DependencyIndexes: file_utilities_proto_events_proto_depIdxs,
		MessageInfos:      file_utilities_proto_events_proto_msgTypes,
	}.Build()
	File_utilities_proto_events_proto = out.File
	file_utilities_proto_events_proto_goTypes = nil
	file_utilities_proto_events_proto_depIdxs = nil
}
